#!/usr/bin/env bash
#
# 실험 ②: 대량 삭제 뒤 autovacuum이 언제 깨어나 얼마나 걸려 죽은 행을 치우는가 —
# autovacuum_vacuum_cost_delay 2ms(기본) vs 0.  (PG-BOOK-EXPERIMENTS.md 카드 ②, DB-IMPROVEMENT-PLAN.md A2)
#
# [실행]
#   ROWS=500000 DELETE_UPTO=450000 ./scripts/db/autovacuum-lab.sh   # 본 판: 순서 2 0 2 0, 50만 행(~280MB), 45만 삭제
#   ORDER="2" ROWS=20000 DELETE_UPTO=18000 ./scripts/db/autovacuum-lab.sh    # 연기 시험
#
# [무엇을 하나]
#   운영과 같은 이미지(pgvector/pgvector:pg17)·같은 메모리 한도(512m)로 일회용 컨테이너를 판마다 새로 띄운다.
#   dockin-db는 건드리지 않는다. 판 하나는:
#     시드(work_logs 꼴, user_id 인덱스) → ANALYZE → 스냅샷[전] → 앞쪽 DELETE_UPTO행 삭제 → 스냅샷[삭제직후]
#     → INTERVAL초마다 n_dead_tup·autovacuum_count·진행 상황·힙 크기를 한 줄씩(timeline.csv)
#     → n_dead_tup이 0이 되면 끝. 스냅샷[후]. 컨테이너 폐기.
#   판 순서는 A→B→A→B로 두어 순서 효과를 상쇄하고, 같은 조건 두 판이 통제군이다(밤 3의 D=A).
#
# [재는 것]
#   wake_s  : 삭제 커밋 ~ pg_stat_progress_vacuum에 work_logs가 처음 보일 때까지. naptime(60s)+임계(20%)의 확인.
#             launcher의 위상에 따라 0~60초가 붙으므로 ±60s는 설계상 잡음이다
#   done_s  : 삭제 커밋 ~ 서버 로그에 work_logs의 "automatic vacuum" 줄이 새로 찍힐 때까지(폴링 INTERVAL 눈금)
#   vacuum_elapsed_s : 그 로그 줄의 elapsed. ★ 본 지표 — 폴링과 무관한 서버 자체 값
#             (첫 실행은 n_dead_tup=0 을 종료 조건으로 썼다가 17개가 남아 영원히 못 끝났다 — "dead but not yet
#              removable"은 0이 되지 않을 수 있다. 그래서 로그 줄 수로 바꿨다)
#   passes  : index_vacuum_count 최대값. 죽은 ID가 메모리에 안 담기면 1을 넘는다
#   heap    : 전/후. 어제 실측(after-bulk-delete.sql 머리말)대로 앞쪽 구멍이라 안 줄어야 정상
#
# [측정이 측정을 방해하는 자리]
#   타임라인 폴링은 통계 뷰와 pg_relation_size만 읽는다 — 힙을 읽지 않는다. 힙을 훑는 pgstattuple_approx는
#   bloat-snapshot.sql에만 있고, 그것은 판당 세 번(전·삭제직후·후)만 부른다.
#
# [절대 시간을 옮겨 적지 말 것]
#   이 호스트·이 컨테이너의 값이다. 볼 것은 2ms↔0의 배수와, 같은 조건 두 판의 폭이다.
#
set -euo pipefail

cd "$(dirname "$0")/../.."

IMAGE=${IMAGE:-pgvector/pgvector:pg17}
NAME=${NAME:-autovac-lab-$(date +%H%M%S)}   # 실행마다 다른 이름. 같은 이름이면 앞선 실행의 trap cleanup이 뒤 실행의 컨테이너를 지운다(2026-09-15)
MEM=${MEM:-512m}
ROWS=${ROWS:-200000}
DELETE_UPTO=${DELETE_UPTO:-180000}
ORDER=${ORDER:-"2 0 2 0"}          # autovacuum_vacuum_cost_delay(ms) 판 순서
INTERVAL=${INTERVAL:-5}
TIMEOUT=${TIMEOUT:-1800}
# 완료 판정이 "removed >= DELETE_UPTO의 90%"라 DELETE_UPTO > ROWS면 절대 못 채우고 TIMEOUT까지 기다린다.
if (( DELETE_UPTO <= 0 || DELETE_UPTO > ROWS )); then
    echo "DELETE_UPTO=$DELETE_UPTO 는 0 < DELETE_UPTO <= ROWS($ROWS) 여야 한다" >&2; exit 2
fi
OUT_DIR=${OUT_DIR:-measure/bloat/autovac-$(date +%Y%m%dT%H%M%S)}

mkdir -p "$OUT_DIR/raw"
RUNS="$OUT_DIR/runs.csv"
echo "run,cost_delay_ms,rows,deleted,wake_s,done_s,vacuum_elapsed_s,autovac_count,passes,heap_before,heap_after,dead_pct_after,free_pct_after" > "$RUNS"

psql_() { docker exec -i "$NAME" psql -U root -d dockindb -X -q -v ON_ERROR_STOP=1 "$@"; }
scalar() { psql_ -t -A -c "$1"; }
snapshot() {   # $1 = 꼬리표
    { echo "# bloat snapshot  $(date +%FT%T%z)  run=$RUN tag=$1"
      psql_ -f - < scripts/db/bloat-snapshot.sql; } > "$OUT_DIR/raw/run$RUN-$1.txt"
}
cleanup() { docker rm -f "$NAME" >/dev/null 2>&1 || true; }
trap cleanup EXIT

{
  echo "# autovacuum lab  $(date +%FT%T%z)"
  echo "image=$IMAGE mem=$MEM rows=$ROWS delete_upto=$DELETE_UPTO order=\"$ORDER\" interval=${INTERVAL}s timeout=${TIMEOUT}s"
  echo "host: $(uname -srm)"; docker version --format 'docker {{.Server.Version}}'
} > "$OUT_DIR/env.md"

RUN=0
for DELAY in $ORDER; do
    RUN=$((RUN+1))
    echo "=== run $RUN  cost_delay=${DELAY}ms ==="
    cleanup
    docker run -d --name "$NAME" --memory="$MEM" \
        -e POSTGRES_USER=root -e POSTGRES_PASSWORD=x -e POSTGRES_DB=dockindb "$IMAGE" \
        -c "autovacuum_vacuum_cost_delay=${DELAY}ms" -c log_autovacuum_min_duration=0 \
        -c lock_timeout=5s -c deadlock_timeout=1s -c log_lock_waits=on >/dev/null
    # entrypoint는 임시 서버로 초기화한 뒤 껐다가 다시 켠다. pg_isready만 보면 임시 서버에 걸려
    # "the database system is shutting down"으로 첫 psql이 죽는다(2026-09-15 실측). 초기화 완료 로그를 먼저 본다.
    for _ in $(seq 1 90); do
        if docker logs "$NAME" 2>&1 | grep -q "PostgreSQL init process complete"            && docker exec "$NAME" pg_isready -U root -d dockindb >/dev/null 2>&1; then break; fi
        sleep 1
    done

    # 시드 — work_logs의 꼴. 본문 ~500B, 작성자 500명. FK 인덱스(V4 idx_work_logs_user)도 같이 둔다.
    psql_ <<EOF
CREATE TABLE work_logs (
    log_id     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title      varchar(256) NOT NULL,
    log_text   text NOT NULL,
    created_at timestamp(6) NOT NULL,
    user_id    varchar(50)
);
INSERT INTO work_logs (title, log_text, created_at, user_id)
SELECT 'lab ' || g, repeat('x', 500), now() - (g || ' seconds')::interval, 'u' || (g % 500)
FROM generate_series(1, $ROWS) g;
CREATE INDEX idx_work_logs_user ON work_logs (user_id);
ANALYZE work_logs;
EOF
    snapshot before
    HEAP_BEFORE=$(scalar "SELECT pg_relation_size('work_logs')")

    # 시드가 INSERT 트리거 autovacuum(PG13+, insert_threshold 1000 + 20%)을 깨운다. 그것이 삭제와 겹치면
    # 두 가지가 꼬인다 — 로그 줄 수가 늘어 "끝"으로 오판하고, 그 VACUUM이 끝나며 n_dead_tup을 자기가 본 값
    # (거의 0)으로 덮어쓴다(2026-09-15에 둘 다 겪었다). 그래서 삭제 전에 그 VACUUM이 끝나기를 기다린다.
    # 운영의 벤치(100만 시드 → 98만 삭제)도 시드 직후 삭제는 아니었으므로 이쪽이 실제에 가깝다.
    vac_lines() { docker logs "$NAME" 2>&1 | grep -c 'automatic vacuum of table "dockindb.public.work_logs"' || true; }
    in_progress() { [[ -n "$(scalar "SELECT 1 FROM pg_stat_progress_vacuum p JOIN pg_class c ON c.oid=p.relid WHERE c.relname='work_logs'")" ]]; }
    echo "  시드 뒤 INSERT 트리거 autovacuum이 지나가기를 기다린다 (naptime 60s + 스캔)"
    for _ in $(seq 1 60); do (( $(vac_lines) >= 1 )) && ! in_progress && break; sleep 5; done
    BASE_LINES=$(vac_lines)
    echo "  기준선: work_logs autovacuum 로그 ${BASE_LINES}줄"

    # 삭제 — 앞쪽. 별도 psql이라 커밋된 채 끝난다(VACUUM이 truncate를 건너뛰는 ③ 조건을 만들지 않는다).
    T0=$(date +%s)
    psql_ -c "DELETE FROM work_logs WHERE log_id <= $DELETE_UPTO"
    snapshot deleted

    TL="$OUT_DIR/run$RUN-timeline.csv"
    echo "t_s,n_live_tup,n_dead_tup,autovacuum_count,phase,heap_blks_scanned,heap_blks_total,index_vacuum_count,heap_bytes" > "$TL"
    WAKE=""; DONE_=""; PASSES=0; SEEN_DEAD=0   # SEEN_DEAD는 타임라인 해석용으로만 남긴다
    while :; do
        T=$(( $(date +%s) - T0 ))
        ROW=$(scalar "SELECT s.n_live_tup, s.n_dead_tup, s.autovacuum_count,
                             COALESCE(p.phase,''), COALESCE(p.heap_blks_scanned,0), COALESCE(p.heap_blks_total,0),
                             COALESCE(p.index_vacuum_count,0), pg_relation_size(s.relid)
                      FROM pg_stat_user_tables s
                      LEFT JOIN pg_stat_progress_vacuum p ON p.relid = s.relid
                      WHERE s.relname = 'work_logs'")
        echo "$T,${ROW//|/,}" >> "$TL"
        IFS='|' read -r _ DEAD AVC PHASE _ _ IVC _ <<< "$ROW"
        [[ -n "$PHASE" && -z "$WAKE" ]] && WAKE=$T
        (( IVC > PASSES )) && PASSES=$IVC
        (( DEAD > 0 )) && SEEN_DEAD=1
        # 끝: 삭제 뒤 새로 찍힌 vacuum 로그 블록의 "tuples: N removed"가 삭제분의 90% 이상이고 진행 중이 아니다.
        # n_dead_tup은 판정에 안 쓴다 — 0이 안 될 수도(17개 "not yet removable"), 다른 VACUUM이 덮어쓸 수도 있다.
        if [[ -z "$PHASE" ]] && (( $(vac_lines) > BASE_LINES )); then
            REMOVED=$(docker logs "$NAME" 2>&1 | awk '/automatic vacuum of table "dockindb.public.work_logs"/{f=1} f && /tuples: [0-9]+ removed/{print; f=0}'                       | tail -1 | grep -o 'tuples: [0-9]*' | grep -o '[0-9]*$' || echo 0)
            if (( REMOVED >= DELETE_UPTO * 9 / 10 )); then DONE_=$T; break; fi
        fi
        if (( T > TIMEOUT )); then echo "  timeout ${TIMEOUT}s" >&2; DONE_="timeout"; break; fi
        sleep "$INTERVAL"
    done
    snapshot after
    HEAP_AFTER=$(scalar "SELECT pg_relation_size('work_logs')")
    read -r DEAD_PCT FREE_PCT <<< "$(scalar "SELECT round(dead_tuple_percent::numeric,1), round(approx_free_percent::numeric,1) FROM pgstattuple_approx('work_logs')" | tr '|' ' ')"
    AVC=$(scalar "SELECT autovacuum_count FROM pg_stat_user_tables WHERE relname='work_logs'")
    # 서버 로그를 통째로 남긴다. log_autovacuum_min_duration=0의 상세(pages/tuples/elapsed/I/O)는 여러 줄이라
    # 첫 줄만 grep하면 경과 시간을 잃는다(2026-09-15 첫 실행에서 그랬다). 폴링 5초보다 이 elapsed가 정확하다.
    docker logs "$NAME" > "$OUT_DIR/raw/run$RUN-postgres.log" 2>&1 || true
    # 각 vacuum 블록의 첫 elapsed만(뒤따르는 automatic analyze의 elapsed를 집지 않게), 그중 마지막 블록.
    VAC_S=$(awk '/automatic vacuum of table "dockindb.public.work_logs"/{f=1} f && /elapsed:/{print; f=0}'                 "$OUT_DIR/raw/run$RUN-postgres.log" | tail -1 | grep -o 'elapsed: [0-9.]*' | grep -o '[0-9.]*$' || true)

    echo "$RUN,$DELAY,$ROWS,$DELETE_UPTO,${WAKE:-},$DONE_,${VAC_S:-},$AVC,$PASSES,$HEAP_BEFORE,$HEAP_AFTER,$DEAD_PCT,$FREE_PCT" >> "$RUNS"
    echo "  wake=${WAKE:-?}s done=${DONE_}s vacuum_elapsed=${VAC_S:-?}s autovac=$AVC passes=$PASSES heap $HEAP_BEFORE -> $HEAP_AFTER dead=${DEAD_PCT}% free=${FREE_PCT}%"
done

echo; echo "$OUT_DIR"; column -s, -t "$RUNS"
