#!/usr/bin/env bash
#
# E2: 스트리밍 복제 standby 하나를 로컬에 띄워 잰다 — 반영 지연·부하 중 지연·읽기 분리·promote.
# (docs/DB-IMPROVEMENT-PLAN.md E2, ADR-0004 3-3의 전제, PG-BOOK-EXPERIMENTS.md 2절 "복제 0건")
#
# [실행]
#   ./scripts/db/replication-lab.sh                       # measure/replication/repl-<ts>/
#   ROWS=100000 LOAD_SEC=30 PROBES=10 ./scripts/db/replication-lab.sh   # 연기 시험
#
# [무엇을 하나]  운영과 같은 이미지·같은 메모리 한도로 일회용 컨테이너 둘. dockin-db는 건드리지 않는다.
#   1. primary 시드(work_logs 꼴 ROWS행) → pg_hba에 replication 허용 → 복제 계정
#   2. standby = pg_basebackup -R (복제 슬롯 사용) → 기동 → pg_stat_replication에 streaming으로 보일 때까지
#   3. 반영 지연(유휴): primary에 표식 행을 넣고 standby가 그 행을 보기까지. PROBES회.
#      측정은 standby 쪽 DO 블록이 한다 — 행이 보이는 순간의 clock_timestamp() − 행에 적힌 primary의 커밋 시각.
#      같은 호스트라 시계가 같고, docker exec 왕복(수십 ms)은 측정 밖이다(대기자를 먼저 띄운다).
#   4. 부하 중 지연: primary에 LOAD_SEC초 동안 배치 INSERT를 걸고 pg_stat_replication의
#      write/flush/replay_lag를 2초마다 + 같은 표식 프로브를 5초마다.
#   5. 읽기 분리: standby에서 SELECT는 되고 INSERT는 거부되는가.
#   6. promote: standby를 승격해 쓰기를 받기까지 몇 초인가. 그 뒤 primary와 갈라진 것(split brain)을 확인.
#
# [절대 시간을 옮겨 적지 말 것] 같은 호스트의 두 컨테이너다. 네트워크가 없다. 볼 것은 자릿수와 부하 전후의 배수다.
#
set -euo pipefail
cd "$(dirname "$0")/../.."

IMAGE=${IMAGE:-pgvector/pgvector:pg17}
MEM=${MEM:-512m}
ROWS=${ROWS:-300000}
LOAD_SEC=${LOAD_SEC:-60}
PROBES=${PROBES:-20}
STAMP=$(date +%Y%m%dT%H%M%S)
NET=${NET:-repl-lab-$STAMP}
P=${P:-repl-primary-$STAMP}
S=${S:-repl-standby-$STAMP}
OUT_DIR=${OUT_DIR:-measure/replication/repl-$STAMP}
REPL_PW=replpw

mkdir -p "$OUT_DIR/raw"
cleanup() { docker rm -f "$P" "$S" >/dev/null 2>&1 || true; docker network rm "$NET" >/dev/null 2>&1 || true; }
trap cleanup EXIT

# -i(stdin 연결)는 heredoc을 먹이는 곳에만 쓴다. -i 붙은 docker exec 둘이 겹치면 한쪽이 20초 넘게 멈추는 것을
# 2026-09-15에 봤다(Windows Docker Desktop, stdin 공유로 추정). 그래서 프로브는 standby 한 세션 안에서 끝낸다(아래).
psqlp() { docker exec "$P" psql -U root -d dockindb -X -q -v ON_ERROR_STOP=1 "$@"; }
psqls() { docker exec "$S" psql -U root -d dockindb -X -q -v ON_ERROR_STOP=1 "$@"; }
psqlp_in() { docker exec -i "$P" psql -U root -d dockindb -X -q -v ON_ERROR_STOP=1 "$@"; }
scalarp() { psqlp -t -A -c "$1"; }
scalars() { psqls -t -A -c "$1"; }
wait_ready() {   # $1=컨테이너. 접속이 되고 SELECT 1이 답하면 준비다.
    # docker logs를 보지 않는다 -- standby는 docker exec -d 로 띄워 PID 1이 아니라 로그가 거기 안 잡힌다.
    for _ in $(seq 1 120); do
        docker exec "$1" psql -U root -d dockindb -X -q -t -A -c "SELECT 1" 2>/dev/null | grep -q '^1$' && return 0
        sleep 1
    done
    echo "!! $1 이 준비되지 않았다" >&2; return 1
}
say() { printf '%s  %s\n' "$(date +%H:%M:%S)" "$*" | tee -a "$OUT_DIR/run.log"; }

{
  echo "# replication lab  $(date +%FT%T%z)"
  echo "image=$IMAGE mem=$MEM rows=$ROWS load_sec=$LOAD_SEC probes=$PROBES"
  echo "host: $(uname -srm)"; docker version --format 'docker {{.Server.Version}}'
} > "$OUT_DIR/env.md"

# ── 1. primary ─────────────────────────────────────────────────────────────
docker network create "$NET" >/dev/null
docker run -d --name "$P" --network "$NET" --memory="$MEM" \
    -e POSTGRES_USER=root -e POSTGRES_PASSWORD=x -e POSTGRES_DB=dockindb "$IMAGE" \
    -c wal_level=replica -c max_wal_senders=5 -c max_replication_slots=5 \
    -c log_lock_waits=on -c lock_timeout=5s >/dev/null
for _ in $(seq 1 90); do docker logs "$P" 2>&1 | grep -q "PostgreSQL init process complete" && break; sleep 1; done
wait_ready "$P"
say "primary 기동. 시드 ${ROWS}행"
T=$(date +%s)
psqlp_in <<EOF
CREATE TABLE work_logs (
    log_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title varchar(256) NOT NULL, log_text text NOT NULL,
    created_at timestamp(6) NOT NULL, user_id varchar(50));
INSERT INTO work_logs (title, log_text, created_at, user_id)
SELECT 'lab '||g, repeat('x',500), now() - (g||' seconds')::interval, 'u'||(g%500) FROM generate_series(1,$ROWS) g;
CREATE INDEX idx_work_logs_user ON work_logs(user_id);
CREATE TABLE probe (k int PRIMARY KEY, sent_at timestamptz NOT NULL);
CREATE ROLE replicator WITH REPLICATION LOGIN PASSWORD '$REPL_PW';
CREATE EXTENSION IF NOT EXISTS dblink;   -- 프로브가 standby 세션 안에서 primary에 INSERT를 쏘는 통로
EOF
SEED_S=$(( $(date +%s) - T ))
# 도커 이미지의 pg_hba는 "host all all all"만 준다. replication 가상 DB는 별도 줄이 필요하다.
docker exec "$P" sh -c 'echo "host replication replicator all scram-sha-256" >> "$PGDATA/pg_hba.conf"'
psqlp -c "SELECT pg_reload_conf()" >/dev/null
HEAP=$(scalarp "SELECT pg_size_pretty(pg_database_size('dockindb'))")
say "시드 ${SEED_S}s, DB ${HEAP}"

# ── 2. standby ─────────────────────────────────────────────────────────────
say "pg_basebackup 으로 standby 생성"
T=$(date +%s)
docker run -d --name "$S" --network "$NET" --memory="$MEM" \
    -e POSTGRES_USER=root -e POSTGRES_PASSWORD=x -e POSTGRES_DB=dockindb "$IMAGE" sleep infinity >/dev/null
# 데이터 디렉터리를 primary 복사본으로 바꿔치기한 뒤 postgres를 직접 띄운다.
# $PGDATA 자체는 이미지의 VOLUME 마운트 지점이라 rm이 안 된다("Device or resource busy") — 안을 비운다.
# -R: standby.signal + primary_conninfo를 써 준다. -C -S: 복제 슬롯을 만들어 primary가 WAL을 지우지 않게.
docker exec -e PGPASSWORD="$REPL_PW" "$S" sh -c '
    find "$PGDATA" -mindepth 1 -delete && chown postgres:postgres "$PGDATA" && chmod 700 "$PGDATA" &&
    su postgres -c "pg_basebackup -c fast -h '"$P"' -U replicator -D \"$PGDATA\" -R -C -S lab_slot -X stream -P" ' \
    > "$OUT_DIR/raw/basebackup.log" 2>&1
BASEBACKUP_S=$(( $(date +%s) - T ))
# docker exec -d 로 띄운 프로세스의 출력은 docker logs에 안 잡힌다(PID 1이 아니다). 파일로 보낸다.
docker exec -d "$S" sh -c 'su postgres -c "postgres -c hot_standby=on -c log_lock_waits=on -c lock_timeout=5s" > /tmp/standby.log 2>&1'
wait_ready "$S"
for _ in $(seq 1 60); do [[ "$(scalarp "SELECT count(*) FROM pg_stat_replication WHERE state='streaming'")" == "1" ]] && break; sleep 1; done
say "standby streaming. basebackup ${BASEBACKUP_S}s"
psqlp -c "SELECT application_name, state, sync_state, write_lag, flush_lag, replay_lag FROM pg_stat_replication" > "$OUT_DIR/raw/replication-initial.txt"
[[ "$(scalars "SELECT pg_is_in_recovery()")" == "t" ]] || { say "!! standby가 recovery 상태가 아니다"; exit 1; }
[[ "$(scalars "SELECT count(*) FROM work_logs")" == "$ROWS" ]] || { say "!! standby 행 수가 다르다"; exit 1; }

# ── 3. 반영 지연(유휴) ────────────────────────────────────────────────────
# 프로브는 standby 한 세션이 전부 한다: dblink로 primary에 표식 행을 넣고(커밋 시각을 행에 적는다),
# 같은 세션에서 그 행이 보일 때까지 2ms 간격으로 돈다(READ COMMITTED라 문장마다 새 스냅샷).
# lag = 보인 순간의 clock_timestamp() − 행의 sent_at. 같은 호스트라 시계가 같다. docker exec 왕복은 측정 밖.
probe() {   # $1=k  → ms 출력
    local k=$1
    docker exec "$S" psql -U root -d dockindb -X -q -t -A -v ON_ERROR_STOP=1 -c "
        DO \$\$ DECLARE t timestamptz; i int := 0; BEGIN
          PERFORM dblink_exec('host=$P dbname=dockindb user=root password=x',
                              'INSERT INTO probe VALUES ($k, clock_timestamp())');
          LOOP SELECT sent_at INTO t FROM probe WHERE k = $k; EXIT WHEN FOUND; i := i+1;
               IF i > 10000 THEN RAISE EXCEPTION 'timeout'; END IF; PERFORM pg_sleep(0.002); END LOOP;
          RAISE NOTICE 'LAG_MS=%', round(extract(epoch FROM clock_timestamp() - t) * 1000, 1);
        END \$\$;" 2>&1 | grep -o 'LAG_MS=[0-9.]*' | cut -d= -f2 || true
}
say "반영 지연(유휴) ${PROBES}회"
echo "k,lag_ms" > "$OUT_DIR/idle-lag.csv"
for k in $(seq 1 "$PROBES"); do echo "$k,$(probe "$k")" >> "$OUT_DIR/idle-lag.csv"; done

# ── 4. 부하 중 지연 ────────────────────────────────────────────────────────
say "부하 ${LOAD_SEC}s — primary에 배치 INSERT, 2초마다 pg_stat_replication, 5초마다 프로브"
echo "t_s,write_lag_ms,flush_lag_ms,replay_lag_ms,sent_minus_replay_bytes" > "$OUT_DIR/load-lag.csv"
echo "t_s,lag_ms" > "$OUT_DIR/load-probe.csv"
docker exec "$P" psql -U root -d dockindb -X -q -c "
    DO \$\$ DECLARE t0 timestamptz := clock_timestamp(); BEGIN
      WHILE clock_timestamp() - t0 < interval '$LOAD_SEC seconds' LOOP
        INSERT INTO work_logs (title, log_text, created_at, user_id)
        SELECT 'load', repeat('y',500), now(), 'load' FROM generate_series(1,2000);
        COMMIT;
      END LOOP; END \$\$;" > "$OUT_DIR/raw/load.log" 2>&1 &
LOAD_PID=$!
T0=$(date +%s); k=$((PROBES)); next_probe=0
while kill -0 $LOAD_PID 2>/dev/null; do
    t=$(( $(date +%s) - T0 ))
    row=$(scalarp "SELECT round(extract(epoch FROM write_lag)*1000,1), round(extract(epoch FROM flush_lag)*1000,1),
                          round(extract(epoch FROM replay_lag)*1000,1), pg_wal_lsn_diff(sent_lsn, replay_lsn)
                   FROM pg_stat_replication LIMIT 1")
    echo "$t,${row//|/,}" >> "$OUT_DIR/load-lag.csv"
    if (( t >= next_probe )); then k=$((k+1)); echo "$t,$(probe "$k")" >> "$OUT_DIR/load-probe.csv"; next_probe=$((t+5)); fi
    sleep 2
done
wait $LOAD_PID || true
LOAD_ROWS=$(scalarp "SELECT count(*) FROM work_logs WHERE user_id='load'")
say "부하 끝: ${LOAD_ROWS}행 삽입"
# 따라잡는 동안에도 2초마다 표본을 남긴다 -- 2026-09-15 판은 backlog 2.2MB에서 0까지 47초의 내역을 못 갈랐다.
# 부하가 끝난 뒤 standby가 따라잡기까지
T=$(date +%s)
for _ in $(seq 1 120); do
    row=$(scalarp "SELECT round(extract(epoch FROM write_lag)*1000,1), round(extract(epoch FROM flush_lag)*1000,1),
                          round(extract(epoch FROM replay_lag)*1000,1), pg_wal_lsn_diff(sent_lsn, replay_lsn)
                   FROM pg_stat_replication LIMIT 1")
    echo "$(( $(date +%s) - T0 )),${row//|/,}" >> "$OUT_DIR/load-lag.csv"
    [[ "${row##*|}" == "0" ]] && break
    sleep 2
done
CATCHUP_S=$(( $(date +%s) - T ))
say "따라잡기 ${CATCHUP_S}s"

# ── 5. 읽기 분리 ───────────────────────────────────────────────────────────
READ_OK=$(scalars "SELECT count(*) FROM work_logs WHERE user_id='u1'")
WRITE_MSG=$(psqls -c "INSERT INTO probe VALUES (999999, now())" 2>&1 || true)
say "standby 읽기: u1 ${READ_OK}행 / 쓰기: ${WRITE_MSG}"

# ── 6. promote ────────────────────────────────────────────────────────────
say "standby promote"
T=$(date +%s%3N)
docker exec "$S" su postgres -c 'pg_ctl promote -D "$PGDATA" -w' > "$OUT_DIR/raw/promote.log" 2>&1
for _ in $(seq 1 200); do [[ "$(scalars "SELECT pg_is_in_recovery()")" == "f" ]] && break; sleep 0.05; done
psqls -c "INSERT INTO probe VALUES (1000000, now())"
PROMOTE_MS=$(( $(date +%s%3N) - T ))
# 갈라짐: 옛 primary에 더 쓰면 두 DB가 다른 미래를 산다. 그것을 숫자로 남긴다.
psqlp -c "INSERT INTO probe VALUES (1000001, now())"
say "promote ${PROMOTE_MS}ms (docker exec 왕복 포함). 갈라짐: 옛 primary에만 k=$(scalarp 'SELECT max(k) FROM probe') / 새 primary에만 k=$(scalars 'SELECT max(k) FROM probe') — 둘 다 자기가 primary라고 믿는다"
psqlp -c "SELECT * FROM pg_stat_replication" > "$OUT_DIR/raw/replication-after-promote.txt"
# 옛 primary에 슬롯이 남으면 WAL을 영원히 보관한다(디스크가 찬다). 운영 promote 절차의 "옛 primary 슬롯 드롭"의 근거.
psqlp -c "SELECT slot_name, active, restart_lsn, pg_size_pretty(pg_wal_lsn_diff(pg_current_wal_lsn(), restart_lsn)) AS retained_wal FROM pg_replication_slots" > "$OUT_DIR/raw/slots-after-promote.txt"
# sh -c 로 감싼다: Git Bash(MSYS)가 첫 인자의 /tmp 를 C:/Users/.../Temp 로 바꿔 넣어 2026-09-15 판의 standby 로그를 잃었다.
docker exec "$S" sh -c 'cat /tmp/standby.log' > "$OUT_DIR/raw/standby-postgres.log" 2>&1 || true
docker logs "$P" > "$OUT_DIR/raw/primary-postgres.log" 2>&1 || true

# ── 요약 ──────────────────────────────────────────────────────────────────
PYTHON=$(command -v python || command -v python3)   # git bash의 python3는 Windows 스토어 스텁이라 "Python"만 찍고 실패한다
"$PYTHON" - "$OUT_DIR" "$SEED_S" "$BASEBACKUP_S" "$CATCHUP_S" "$PROMOTE_MS" "$LOAD_ROWS" "$HEAP" <<'PY'
import csv, sys, statistics as st
out, seed, bb, catch, prom, rows, heap = sys.argv[1:]
def col(f, name):
    with open(f"{out}/{f}") as fh:
        return [float(r[name]) for r in csv.DictReader(fh) if r[name] not in ('', 'None')]
idle = col("idle-lag.csv", "lag_ms"); lp = col("load-probe.csv", "lag_ms"); rl = col("load-lag.csv", "replay_lag_ms")
q = lambda v, p: sorted(v)[min(len(v)-1, int(len(v)*p))] if v else float('nan')
lines = [
 "| 항목 | 값 |", "|---|---|",
 f"| DB 크기 | {heap} (시드 {seed}s) |",
 f"| pg_basebackup | {bb}s |",
 f"| 반영 지연(유휴, n={len(idle)}) | p50 {q(idle,.5)} · p95 {q(idle,.95)} · max {max(idle) if idle else 'nan'} ms |",
 f"| 반영 지연(부하 중 프로브, n={len(lp)}) | p50 {q(lp,.5)} · p95 {q(lp,.95)} · max {max(lp) if lp else 'nan'} ms |",
 f"| replay_lag(부하 중, pg_stat_replication, n={len(rl)}) | p50 {q(rl,.5)} · max {max(rl) if rl else 'nan'} ms |",
 f"| 부하 | {rows}행 삽입, 끝난 뒤 따라잡기 {catch}s |",
 f"| promote → 쓰기 가능 | {prom} ms |",
]
open(f"{out}/summary.md","w",encoding="utf-8").write("\n".join(lines)+"\n"); print("\n".join(lines))
PY
say "산출물: $OUT_DIR"
