#!/usr/bin/env bash
#
# D1: pg_trgm GIN 인덱스가 작업일지 검색(LIKE %kw%)에 얼마나 도움이 되고, 무엇을 대가로 내는가.
# (docs/DB-IMPROVEMENT-PLAN.md D1, PG-BOOK-EXPERIMENTS.md 카드 ④, WORK-BACKLOG P2-15-5 ⑤ "B-tree로 안 변한다"의 다음 질문)
#
# [실행]
#   ./scripts/db/trgm-lab.sh                          # 본 판: 100만 행, 패스 A B A B  → measure/trgm/trgm-<ts>/
#   ROWS=50000 PASSES="A B" ./scripts/db/trgm-lab.sh  # 연기 시험
#
# [무엇을 하나]
#   운영과 같은 이미지·512MB 한도로 일회용 컨테이너 하나. dockin-db는 건드리지 않는다.
#   work_logs 꼴 ROWS행(본문은 CorpusSeedGeneratorTest의 조합 규칙 — 어휘가 실제와 같아 트라이그램 다양성이 실제에 가깝다.
#   행 길이 259자 근처, 1/10,000행에만 희귀 문장, 500명·6구역은 WorkLogListBenchmarkTest와 같다)
#   → VACUUM ANALYZE → 패스 순서대로:
#     A = pg_trgm 인덱스 없음 (user_id B-tree만, 운영 스키마 V4와 같다)
#     B = title·log_text에 gin_trgm_ops GIN 둘 (검색이 OR로 두 컬럼을 보므로 둘 다 필요하다)
#   패스마다: pg_prewarm(read) → 검색 다섯 개를 각각 2회 워밍업 + 5회 측정(\timing) → EXPLAIN (ANALYZE, BUFFERS) 한 번
#            → 쓰기 비용: 50,000행 INSERT 시간 → 그 행 삭제 + VACUUM.
#   B 패스의 첫 번째는 CREATE INDEX CONCURRENTLY(docs/db/online-ddl.md 절차의 첫 실전), 두 번째는 일반 CREATE INDEX —
#   빌드 시간 둘을 나란히 둔다. 인덱스 크기는 만들 때마다 기록.
#   A→B→A→B: 같은 조건 두 패스가 통제군이다(autovacuum-lab과 같은 설계).
#
# [검색 다섯 개 — 왜 이 다섯인가]
#   실제 SQL은 WorkLogRepository.searchWorkLogs: 구역 84명 IN + (title LIKE OR log_text LIKE) + 커서 + ORDER BY + LIMIT 20.
#   Q1 실제 SQL, 희귀 4자 '크랭크축' (100만 중 100행)      ← GIN이 제일 잘 도울 자리
#   Q2 실제 SQL, 흔한 3자 '베어링'  (약 1/4 행: 부위·원인·조치 어휘에 들어 있다) ← LIMIT 20이 순차 스캔을 일찍 끊는다. GIN이 손해일 후보
#   Q3 실제 SQL, 희귀 2자 '균열'   (100행)                 ← pg_trgm은 3자 미만 조각에서 트라이그램을 못 뽑는다. 한국어 검색어는 2자가 흔하다
#   Q4 실제 SQL, 흔한 2자 '마모'   (약 1/10 행: 원인 '베어링 마모')
#   Q5 벤치 ⑤ 원문(구역 필터 없음, 정렬 없음) '크랭크축'    ← P2-15-5의 432ms와 잇는 줄
#
# [절대 시간을 옮겨 적지 말 것]  이 호스트 값이다. 볼 것은 A↔B의 배수, 같은 조건 두 패스의 폭, 실행계획의 노드.
#
set -euo pipefail
cd "$(dirname "$0")/../.."

IMAGE=${IMAGE:-pgvector/pgvector:pg17}
MEM=${MEM:-512m}
ROWS=${ROWS:-1000000}
RARE_EVERY=${RARE_EVERY:-10000}
USERS=${USERS:-500}
AREAS=${AREAS:-6}
WRITE_ROWS=${WRITE_ROWS:-50000}
PASSES=${PASSES:-"A B A B"}
STAMP=$(date +%Y%m%dT%H%M%S)
C=${C:-trgm-lab-$STAMP}
OUT_DIR=${OUT_DIR:-measure/trgm/trgm-$STAMP}

mkdir -p "$OUT_DIR/raw"
cleanup() { docker rm -f "$C" >/dev/null 2>&1 || true; }
trap cleanup EXIT

psqlc() { docker exec "$C" psql -U root -d dockindb -X -q -v ON_ERROR_STOP=1 "$@"; }
psqli() { docker exec -i "$C" psql -U root -d dockindb -X -q -v ON_ERROR_STOP=1 "$@"; }
scalar() { psqlc -t -A -c "$1"; }
say() { printf '%s  %s\n' "$(date +%H:%M:%S)" "$*" | tee -a "$OUT_DIR/run.log"; }
ms_now() { date +%s%3N; }

{
  echo "# trgm lab  $(date +%FT%T%z)"
  echo "image=$IMAGE mem=$MEM rows=$ROWS rare_every=$RARE_EVERY users=$USERS areas=$AREAS write_rows=$WRITE_ROWS passes=\"$PASSES\""
  echo "host: $(uname -srm)"; docker version --format 'docker {{.Server.Version}}'
} > "$OUT_DIR/env.md"

# ── 컨테이너 ────────────────────────────────────────────────────────────────
docker run -d --name "$C" --memory="$MEM" \
    -e POSTGRES_USER=root -e POSTGRES_PASSWORD=x -e POSTGRES_DB=dockindb "$IMAGE" \
    -c lock_timeout=5s -c log_lock_waits=on -c shared_preload_libraries=pg_stat_statements \
    -c synchronize_seqscans=off >/dev/null   # 켜 두면 순차 스캔이 직전 스캔이 멈춘 자리에서 시작해 LIMIT 20의 조기 종료가 12ms↔720ms로 흔들린다(첫 판)
for _ in $(seq 1 90); do docker logs "$C" 2>&1 | grep -q "PostgreSQL init process complete" && break; sleep 1; done
for _ in $(seq 1 60); do docker exec "$C" psql -U root -d dockindb -X -q -t -A -c "SELECT 1" 2>/dev/null | grep -q '^1$' && break; sleep 1; done
say "컨테이너 기동. 시드 ${ROWS}행"
psqlc -c "SELECT name, setting, unit FROM pg_settings WHERE name IN ('shared_buffers','work_mem','maintenance_work_mem','effective_cache_size','max_parallel_workers_per_gather','random_page_cost')" > "$OUT_DIR/raw/settings.txt"

# ── 시드 (WorkLogListBenchmarkTest.load 와 같은 분포) ───────────────────────
T=$(ms_now)
psqli <<EOF
CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE EXTENSION IF NOT EXISTS pg_prewarm;
CREATE TABLE work_logs (
    log_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title varchar(256) NOT NULL, log_text text NOT NULL,
    created_at timestamp(6) NOT NULL, updated_at timestamp(6),
    user_id varchar(50) NOT NULL, equipment_id bigint);
-- 본문은 CorpusSeedGeneratorTest.bodyKo()의 조합 규칙을 SQL로 옮긴 것이다(설비×부위×증상×원인×조치×후속, 같은 어휘).
-- WorkLogListBenchmarkTest처럼 한 문장을 8번 반복하면 트라이그램 종류가 수십 개뿐이라 GIN 크기·빌드 시간이
-- 실제보다 한참 작게 나온다 — 이 실험이 재려는 게 바로 그 대가라 어휘 다양성을 실제 코퍼스와 맞춘다.
-- 행 길이는 그래도 259자 근처(로컬 코퍼스 평균)로 맞아, 순차 스캔이 읽는 페이지 수는 벤치와 같은 자릿수다.
-- 곱수는 표 크기와 서로소여야 한다 — 첫 판(2026-09-16)은 원인이 (i*5)%10이라 열 개 중 둘만 나왔고 '마모'가 코퍼스에 없었다.
CREATE TABLE lex_equipment AS SELECT * FROM unnest(ARRAY['CO2 용접기','겐트리 크레인','무인 도장설비','플라즈마 절단기','고소작업대','유압 프레스','블라스팅 장비','이송 컨베이어','공기압축기','집진 설비','지게차','발전기']) WITH ORDINALITY AS t(w, n);
CREATE TABLE lex_part AS SELECT * FROM unnest(ARRAY['송급 롤러','유압 실린더','제어 패널','베어링부','감속기','배관 플랜지','전동기 축','냉각 팬','안전 스위치','케이블 그랜드']) WITH ORDINALITY AS t(w, n);
CREATE TABLE lex_symptom AS SELECT * FROM unnest(ARRAY['이상 진동이 발생했다','간헐적으로 정지했다','온도가 규정치를 넘었다','누유가 확인되었다','소음이 평소보다 커졌다','출력이 불안정했다','경보가 반복 발생했다','동작이 지연되었다','압력이 유지되지 않았다','표시값이 튀는 현상이 있었다','기동에 실패했다','과전류로 차단되었다']) WITH ORDINALITY AS t(w, n);
CREATE TABLE lex_cause AS SELECT * FROM unnest(ARRAY['체결 볼트 이완이','윤활 부족이','필터 막힘이','센서 접점 불량이','절연 저하가','개스킷 경화가','베어링 마모가','냉각수 부족이','제어 파라미터 오설정이','이물질 유입이']) WITH ORDINALITY AS t(w, n);
CREATE TABLE lex_action AS SELECT * FROM unnest(ARRAY['규정 토크로 재체결했다','그리스를 보충했다','필터를 교체했다','접점을 청소하고 재결선했다','절연 저항을 측정하고 케이블을 교체했다','개스킷을 신품으로 교체했다','베어링을 교체하고 정렬을 재조정했다','냉각수를 보충하고 누설 여부를 확인했다','파라미터를 기준값으로 되돌렸다','내부를 분해 청소했다','임시 조치 후 정비팀에 이관했다','예비품으로 교체했다']) WITH ORDINALITY AS t(w, n);
CREATE TABLE lex_follow AS SELECT * FROM unnest(ARRAY['다음 정기 점검에서 재확인이 필요하다.','동일 증상이 재발하면 부품 수명 도래로 보고 교체를 건의한다.','점검 주기를 단축하자고 반장에게 보고했다.','예비품 재고가 없어 발주를 요청했다.','인접 호기에서도 같은 증상이 있는지 확인하기로 했다.','작업 표준서에 이 절차가 빠져 있어 추가를 요청했다.','교대조에 경과 관찰을 인계했다.','원인이 완전히 규명되지 않아 기록만 남긴다.','재발 방지를 위해 체결 이력을 기록하기로 했다.','설비 이력 카드에 반영했다.']) WITH ORDINALITY AS t(w, n);
EOF
# 시드와 쓰기 비용 측정이 같은 본문 생성 SQL을 쓴다 — 쓰기 쪽만 단조로운 문장이면 GIN 유지 비용이 실제보다 싸게 나온다.
# SQL 함수로 감쌌더니 행마다 조인이 다시 돌아 50,000행에 306s가 걸렸다(2026-09-16). 한 문장의 JOIN으로 두면 해시 조인 한 번이다.
gen_rows() {   # $1=제목 접두사  $2=generate_series 인자  $3=i 오프셋(예: "+ 1000000")  $4=희귀 문장 CASE(없으면 빈 문자열)
    cat <<SQL
SELECT '$1' || e.w || ' ' || (1 + i % 7) || '호기 ' || p.w,
       e.w || ' ' || (1 + i % 7) || '호기 ' || p.w || '에서 ' || s.w || '. '
         || '점검 결과 ' || c.w || ' 원인으로 확인되었다. ' || a.w || '. '
         || '조치 후 ' || (10 + (i * 7) % 50) || '분간 시운전하여 정상 동작을 확인했다. '
         || '측정값은 ' || ((i * 13) % 90) || '.' || (i % 10) || '이며 기준 범위 이내였다. '
         || f.w $4,
       TIMESTAMP '2024-08-01 06:00:00' + (i * INTERVAL '1 minute'),
       TIMESTAMP '2024-08-01 06:00:00' + (i * INTERVAL '1 minute'),
       'bch' || lpad((i % $USERS)::text, 4, '0'),
       NULL
  FROM (SELECT g $3 AS i FROM generate_series($2) AS g) gs
  JOIN lex_equipment e ON e.n = 1 + (i * 7) % 12
  JOIN lex_part p      ON p.n = 1 + (i * 3) % 10
  JOIN lex_symptom s   ON s.n = 1 + (i * 11) % 12
  JOIN lex_cause c     ON c.n = 1 + (i * 7) % 10
  JOIN lex_action a    ON a.n = 1 + (i * 17) % 12
  JOIN lex_follow f    ON f.n = 1 + (i * 19) % 10
SQL
}
psqli <<EOF
INSERT INTO work_logs (title, log_text, created_at, updated_at, user_id, equipment_id)
$(gen_rows '[벤치] ' "1, $ROWS" "" "|| CASE WHEN i % $RARE_EVERY = 0 THEN ' 특이사항으로 크랭크축 균열을 발견했다.' ELSE '' END");
CREATE INDEX idx_work_logs_user ON work_logs (user_id);   -- V4, 운영 스키마와 같다
EOF
SEED_MS=$(( $(ms_now) - T ))
# 수동 VACUUM이 n_ins_since_vacuum을 0으로 — INSERT 트리거 autovacuum이 측정 중에 안 온다(autovac lab의 부수 발견).
# ANALYZE는 따로 잰다: en_US.utf8에서 한국어 본문 30,000행 표본을 strcoll로 정렬하느라 행 수와 무관하게 수십 초가 든다
# (연기 시험 2026-09-16: 20,000행에서 log_text 42s·title 11s, COLLATE "C"면 0.4s). 운영 autovacuum의 analyze도 같은 값을 문다.
T=$(ms_now); psqlc -c "VACUUM work_logs"; VAC_MS=$(( $(ms_now) - T ))
T=$(ms_now); psqlc -c "ANALYZE work_logs"; ANALYZE_MS=$(( $(ms_now) - T ))
HEAP=$(scalar "SELECT pg_size_pretty(pg_relation_size('work_logs'))")
say "시드 $((SEED_MS/1000))s, VACUUM $((VAC_MS/1000))s, ANALYZE $((ANALYZE_MS/1000))s, 힙 $HEAP, 희귀 행 $(scalar "SELECT count(*) FROM work_logs WHERE log_text LIKE '%크랭크축%'")건"
echo "seed_ms=$SEED_MS vacuum_ms=$VAC_MS analyze_ms=$ANALYZE_MS heap=$HEAP" >> "$OUT_DIR/env.md"

# ── 검색 SQL ─────────────────────────────────────────────────────────────────
# 구역 0의 84명: i % 500 이 0,6,12,... 인 사용자. WorkLogListBenchmarkTest.ownersInArea(0)과 같다.
IN_LIST=$(python -c "print(','.join(\"'bch%04d'\" % i for i in range(0, $USERS, $AREAS)))")
real_sql() {   # $1=키워드. Hibernate가 searchWorkLogs에서 내는 문장 꼴(커서 null = 첫 페이지)
    echo "SELECT * FROM work_logs w WHERE w.user_id IN ($IN_LIST) AND (w.title LIKE '%$1%' OR w.log_text LIKE '%$1%') AND (CAST(NULL AS timestamp) IS NULL OR w.created_at < NULL OR (w.created_at = NULL AND w.log_id < NULL)) ORDER BY w.created_at DESC, w.log_id DESC LIMIT 20"
}
declare -A Q
Q[Q1]=$(real_sql '크랭크축')
Q[Q2]=$(real_sql '베어링')
Q[Q3]=$(real_sql '균열')
Q[Q4]=$(real_sql '마모')
Q[Q5]="SELECT * FROM work_logs WHERE title LIKE '%크랭크축%' OR log_text LIKE '%크랭크축%' LIMIT 20"
QORDER="Q1 Q2 Q3 Q4 Q5"
{ for q in $QORDER; do echo "-- $q"; echo "${Q[$q]}"; echo; done; } > "$OUT_DIR/queries.sql"

echo "pass,state,query,run,ms" > "$OUT_DIR/timings.csv"
echo "pass,state,index,build_kind,build_ms,size" > "$OUT_DIR/indexes.csv"
echo "pass,state,round,write_rows,insert_ms" > "$OUT_DIR/writes.csv"

prewarm() {
    scalar "SELECT coalesce(sum(pg_prewarm(c.oid, 'read')), 0) FROM pg_class c WHERE c.oid = 'work_logs'::regclass OR c.oid IN (SELECT indexrelid FROM pg_index WHERE indrelid = 'work_logs'::regclass)"
}

# 한 패스의 검색 측정: psql 세션 하나에서 \timing 으로 7회씩. docker exec 왕복은 세션 밖이라 측정에 안 들어간다.
measure_pass() {   # $1=pass번호 $2=state(A|B)
    local pass=$1 state=$2 f="$OUT_DIR/raw/pass${pass}-${state}-timing.txt"
    {
      echo '\o /dev/null'      # 결과는 버린다. 메타 명령이라 Git Bash의 경로 변환(-o /dev/null → NUL)을 안 탄다
      echo '\timing on'
      echo '\pset pager off'
      for q in $QORDER; do
        for r in 1 2 3 4 5 6 7; do echo "\\echo == $q run $r"; echo "${Q[$q]};"; done
      done
    } | psqli > "$f" 2>&1 || true
    # 출력에는 "== Q1 run 1" 뒤에 "Time: 12.345 ms" 가 온다
    awk -v pass="$pass" -v state="$state" '
        /^== /   { q=$2; r=$4 }
        /^Time: / { sub(/ ms/, "", $2); print pass "," state "," q "," r "," $2 }' "$f" >> "$OUT_DIR/timings.csv"
    for q in $QORDER; do
        { echo "-- $q"; psqlc -c "EXPLAIN (ANALYZE, BUFFERS) ${Q[$q]}"; echo; } >> "$OUT_DIR/raw/pass${pass}-${state}-plans.txt"
    done
}

write_cost() {   # $1=pass $2=state. 50,000행 INSERT 한 문장 × 3회 — 실제 쓰기는 한 행씩이지만 인덱스 유지 비용의 배수는 같은 방향이다.
    local pass=$1 state=$2 T ms out=""   # 한 번만 재면 같은 A끼리 4.4s↔11.5s였다(첫 판). 세 번 재고 요약은 중앙값.
    for round in 1 2 3; do
        T=$(ms_now)
        psqli >/dev/null <<EOF
INSERT INTO work_logs (title, log_text, created_at, updated_at, user_id, equipment_id)
$(gen_rows '[쓰기] ' "1, $WRITE_ROWS" "+ $ROWS" "");
EOF
        ms=$(( $(ms_now) - T ))
        echo "$pass,$state,$round,$WRITE_ROWS,$ms" >> "$OUT_DIR/writes.csv"
        psqlc -c "DELETE FROM work_logs WHERE title LIKE '[쓰기] %'" >/dev/null
        psqlc -c "VACUUM work_logs" >/dev/null
        out="$out $ms"
    done
    echo "$out"
}

build_index() {   # $1=pass $2=kind(concurrently|plain) $3=name $4=column
    local pass=$1 kind=$2 name=$3 col=$4 T ms kw=""
    [[ $kind == concurrently ]] && kw="CONCURRENTLY"
    T=$(ms_now)
    psqlc -c "CREATE INDEX $kw $name ON work_logs USING gin ($col gin_trgm_ops)" >/dev/null
    ms=$(( $(ms_now) - T ))
    local size; size=$(scalar "SELECT pg_size_pretty(pg_relation_size('$name'))")
    echo "$pass,B,$name,$kind,$ms,$size" >> "$OUT_DIR/indexes.csv"
    say "  $name ($kind) 빌드 $((ms/1000))s, 크기 $size"
}

# ── 패스 ────────────────────────────────────────────────────────────────────
pass=0; b_count=0
for state in $PASSES; do
    pass=$((pass+1))
    if [[ $state == B ]]; then
        b_count=$((b_count+1))
        kind=$([[ $b_count -eq 1 ]] && echo concurrently || echo plain)
        say "패스 $pass [B] GIN 인덱스 생성 ($kind)"
        build_index "$pass" "$kind" idx_trgm_work_logs_title title
        build_index "$pass" "$kind" idx_trgm_work_logs_log_text log_text
        psqlc -c "SELECT indexrelid::regclass, indisvalid FROM pg_index WHERE NOT indisvalid" | grep -q '0 rows' || say "!! invalid 인덱스가 있다"
    else
        psqlc -c "DROP INDEX IF EXISTS idx_trgm_work_logs_title; DROP INDEX IF EXISTS idx_trgm_work_logs_log_text" >/dev/null
    fi
    T=$(ms_now); psqlc -c "ANALYZE work_logs" >/dev/null; ANALYZE_MS=$(( $(ms_now) - T ))
    warmed=$(prewarm)
    say "패스 $pass [$state] ANALYZE $((ANALYZE_MS/1000))s, prewarm ${warmed}블록, 검색 5개 × 7회"
    measure_pass "$pass" "$state"
    say "패스 $pass [$state] 쓰기 ${WRITE_ROWS}행 × 3:$(write_cost "$pass" "$state") ms"
done
psqlc -c "SELECT pg_size_pretty(pg_relation_size('work_logs')) heap, pg_size_pretty(pg_indexes_size('work_logs')) indexes, pg_size_pretty(pg_total_relation_size('work_logs')) total" > "$OUT_DIR/raw/sizes-final.txt"
docker logs "$C" > "$OUT_DIR/raw/postgres.log" 2>&1 || true

# ── 요약 ────────────────────────────────────────────────────────────────────
PYTHON=$(command -v python || command -v python3)
"$PYTHON" - "$OUT_DIR" "$HEAP" <<'PY'
import csv, sys, statistics as st
from collections import defaultdict
out, heap = sys.argv[1:]
t = defaultdict(list)
for r in csv.DictReader(open(f"{out}/timings.csv")):
    if int(r["run"]) > 2:   # 1·2회는 워밍업
        t[(int(r["pass"]), r["state"], r["query"])].append(float(r["ms"]))
passes = sorted({k[0] for k in t}); queries = ["Q1","Q2","Q3","Q4","Q5"]
names = {"Q1":"실제 SQL · 희귀 4자 '크랭크축'","Q2":"실제 SQL · 흔함 3자 '베어링'","Q3":"실제 SQL · 희귀 2자 '균열'","Q4":"실제 SQL · 흔함 2자 '마모'","Q5":"벤치 ⑤ 원문 · '크랭크축'"}
state_of = {p: next(k[1] for k in t if k[0]==p) for p in passes}
hdr = "| 검색 | " + " | ".join(f"패스{p} {state_of[p]}" for p in passes) + " | A→B |"
lines = [f"힙 {heap}", "", hdr, "|---|" + "---|"*len(passes) + "---|"]
for q in queries:
    cells = [f"{st.median(t[(p,state_of[p],q)]):.1f}" for p in passes]
    a = [st.median(t[(p,'A',q)]) for p in passes if state_of[p]=='A']; b = [st.median(t[(p,'B',q)]) for p in passes if state_of[p]=='B']
    ratio = f"{st.mean(a)/st.mean(b):.1f}배" if a and b and st.mean(b)>0 else "-"
    lines.append(f"| {names[q]} | " + " | ".join(cells) + f" | {ratio} |")
lines += ["", "(ms, 5회 중앙값. 1·2회 워밍업 제외)", "", "| 패스 | 인덱스 | 빌드 | 시간 | 크기 |", "|---|---|---|---|---|"]
for r in csv.DictReader(open(f"{out}/indexes.csv")):
    lines.append(f"| {r['pass']} | {r['index']} | {r['build_kind']} | {int(r['build_ms'])/1000:.1f}s | {r['size']} |")
w = defaultdict(list); wrows = 0
for r in csv.DictReader(open(f"{out}/writes.csv")):
    w[(int(r["pass"]), r["state"])].append(int(r["insert_ms"])/1000); wrows = int(r["write_rows"])
lines += ["", f"| 패스 | 상태 | INSERT {wrows:,}행 × 3 | 중앙값 |", "|---|---|---|---|"]
for (p, s), v in sorted(w.items()):
    lines.append(f"| {p} | {s} | {' / '.join(f'{x:.1f}' for x in v)} | {st.median(v):.1f}s |")
wa = [st.median(v) for (p, s), v in w.items() if s == 'A']; wb = [st.median(v) for (p, s), v in w.items() if s == 'B']
if wa and wb: lines.append(f"\n쓰기 A→B: {st.mean(wb)/st.mean(wa):.1f}배 (중앙값들의 평균끼리)")
open(f"{out}/summary.md","w",encoding="utf-8").write("\n".join(lines)+"\n"); print("\n".join(lines))
PY
say "산출물: $OUT_DIR"
