-- 무중단 DDL 절차 검증용 표본 (docs/db/online-ddl.md). 운영 스키마와 무관하다.
CREATE TABLE lab_rows (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, v text NOT NULL);
INSERT INTO lab_rows (v) SELECT 'r' || g FROM generate_series(1, 20000) g;
