-- ===========================================================================
-- PostgreSQL 실제 스키마 (참조용 · 생성물)
--
-- 이 파일은 손으로 쓰는 것이 아니라 **떠 있는 DB에서 뽑은 덤프**다.
-- 실행하지 않으며, 실행할 필요도 없다. 목적은 하나 -- "지금 스키마가 어떻게 생겼는지"를
-- 엔티티 22개를 열어보지 않고 확인할 수 있게 하는 것.
--
-- 소스 오브 트루스가 아니다.
--   - 대부분의 테이블: JPA 엔티티 + Hibernate ddl-auto=update 가 만든다
--   - document_chunks / 확장 / HNSW 인덱스: Flyway V1 이 만든다
--   - src/main/resources/schema.sql: MySQL 문법이며 실행되지 않는 stale 문서다 (인용 금지)
--
-- 갱신 방법:
--   docker compose up -d DOCKin-DB
--   docker exec dockin-db pg_dump -U root -d dockindb --schema-only --no-owner --no-privileges
--
-- 스키마를 바꿨는데 이 파일을 안 고쳐도 아무도 모른다. 그래서 이 파일은 신뢰의 근거가 아니라
-- 읽기 편의를 위한 사본이며, 엔티티와의 일치는 SchemaValidationTest 가 검증한다.
--
-- 뽑은 시점: 2026-08-05 (DB 생성 2026-08-04, PostgreSQL 이관 시점)
--
-- 알려진 잉여 항목:
--   - bench_leave_balance : LeaveBalanceConcurrencyTest 가 만드는 벤치마크 전용 테이블.
--                           엔티티가 없으며 애플리케이션은 쓰지 않는다.
--   - flyway_schema_history : Flyway 자체 관리 테이블
-- ===========================================================================

--
-- PostgreSQL database dump
--

\restrict cpzfiLeZvkNnIA33XXGc3xcQ7QgtYMZnU09uiE2OiJDykK5fdXgEJMKsQ6LDO5w

-- Dumped from database version 17.10 (Debian 17.10-1.pgdg12+1)
-- Dumped by pg_dump version 17.10 (Debian 17.10-1.pgdg12+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: pg_stat_statements; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS pg_stat_statements WITH SCHEMA public;


--
-- Name: EXTENSION pg_stat_statements; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION pg_stat_statements IS 'track planning and execution statistics of all SQL statements executed';


--
-- Name: vector; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS vector WITH SCHEMA public;


--
-- Name: EXTENSION vector; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION vector IS 'vector data type and ivfflat and hnsw access methods';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: absence_requests; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.absence_requests (
    request_id integer NOT NULL,
    decision_comment character varying(255),
    document_url character varying(255),
    end_date date NOT NULL,
    processed_at timestamp(6) without time zone,
    reason character varying(255) NOT NULL,
    requested_at timestamp(6) without time zone,
    start_date date NOT NULL,
    status character varying(20) NOT NULL,
    request_type character varying(20) NOT NULL,
    user_id character varying(50) NOT NULL,
    processed_by character varying(50),
    CONSTRAINT absence_requests_request_type_check CHECK (((request_type)::text = ANY ((ARRAY['VACATION'::character varying, 'SICK'::character varying])::text[]))),
    CONSTRAINT absence_requests_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying])::text[])))
);


--
-- Name: absence_requests_request_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.absence_requests ALTER COLUMN request_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.absence_requests_request_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: attendance; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.attendance (
    id bigint NOT NULL,
    clock_in_time timestamp(6) without time zone,
    clock_out_time timestamp(6) without time zone,
    in_location character varying(255),
    out_location character varying(255),
    status character varying(20) NOT NULL,
    total_work_time character varying(255),
    work_date date NOT NULL,
    user_id character varying(50) NOT NULL,
    CONSTRAINT attendance_status_check CHECK (((status)::text = ANY ((ARRAY['NORMAL'::character varying, 'LATE'::character varying, 'LEFT_EARLY'::character varying, 'ABSENT'::character varying, 'VACATION'::character varying, 'SICK'::character varying])::text[])))
);


--
-- Name: attendance_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.attendance_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: authority; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.authority (
    log_id bigint NOT NULL,
    authority smallint,
    member_id character varying(50),
    CONSTRAINT authority_authority_check CHECK (((authority >= 0) AND (authority <= 1)))
);


--
-- Name: authority_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.authority ALTER COLUMN log_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.authority_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: bench_leave_balance; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.bench_leave_balance (
    user_id character varying(50) NOT NULL,
    remaining_leave_days integer NOT NULL
);


--
-- Name: chat_history; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.chat_history (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    reply text,
    retrieval_mode character varying(16),
    source_chunk_ids text,
    trace_id character varying(255),
    user_id character varying(255),
    user_query text
);


--
-- Name: chat_history_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.chat_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chat_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: chat_members; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.chat_members (
    id integer NOT NULL,
    joined_at timestamp(6) without time zone,
    last_read_time timestamp(6) without time zone,
    room_id integer NOT NULL,
    user_id character varying(50) NOT NULL
);


--
-- Name: chat_members_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.chat_members ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chat_members_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: chat_messages; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.chat_messages (
    message_id bigint NOT NULL,
    content text NOT NULL,
    file_url character varying(255),
    message_type character varying(255) NOT NULL,
    sender_id character varying(255) NOT NULL,
    sent_at timestamp(6) without time zone,
    room_id integer NOT NULL,
    CONSTRAINT chat_messages_message_type_check CHECK (((message_type)::text = ANY ((ARRAY['TEXT'::character varying, 'IMAGE'::character varying, 'FILE'::character varying])::text[])))
);


--
-- Name: chat_messages_message_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.chat_messages ALTER COLUMN message_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chat_messages_message_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: chat_rooms; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.chat_rooms (
    room_id integer NOT NULL,
    created_at timestamp(6) without time zone,
    creator_id character varying(255),
    is_group boolean,
    last_message_at timestamp(6) without time zone,
    last_message_content character varying(255),
    room_name character varying(255)
);


--
-- Name: chat_rooms_room_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.chat_rooms ALTER COLUMN room_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chat_rooms_room_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: checklist_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.checklist_items (
    item_id integer NOT NULL,
    content character varying(255) NOT NULL,
    sequence integer NOT NULL,
    checklist_id integer NOT NULL
);


--
-- Name: checklist_items_item_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.checklist_items ALTER COLUMN item_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.checklist_items_item_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: checklist_results; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.checklist_results (
    result_id integer NOT NULL,
    checked_at timestamp(6) without time zone NOT NULL,
    is_checked boolean NOT NULL,
    checklist_item_id integer NOT NULL,
    user_id character varying(50) NOT NULL
);


--
-- Name: checklist_results_result_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.checklist_results ALTER COLUMN result_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.checklist_results_result_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: checklists; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.checklists (
    checklist_id integer NOT NULL,
    created_at timestamp(6) without time zone,
    phase character varying(10) NOT NULL,
    title character varying(100) NOT NULL,
    updated_at timestamp(6) without time zone,
    equipment_id bigint NOT NULL,
    CONSTRAINT checklists_phase_check CHECK (((phase)::text = ANY ((ARRAY['PRE'::character varying, 'POST'::character varying])::text[])))
);


--
-- Name: checklists_checklist_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.checklists ALTER COLUMN checklist_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.checklists_checklist_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: document_chunk_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.document_chunk_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: document_chunks; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.document_chunks (
    chunk_id bigint NOT NULL,
    chunk_index integer NOT NULL,
    content text NOT NULL,
    content_hash character varying(64) NOT NULL,
    created_at timestamp(6) without time zone,
    embedding public.vector(384) NOT NULL,
    embedding_dim integer NOT NULL,
    embedding_model character varying(64) NOT NULL,
    language_code character varying(10),
    owner_user_id character varying(50),
    source_id bigint NOT NULL,
    source_type character varying(32) NOT NULL,
    updated_at timestamp(6) without time zone,
    visibility character varying(16) NOT NULL,
    CONSTRAINT document_chunks_source_type_check CHECK (((source_type)::text = ANY ((ARRAY['WORK_LOG'::character varying, 'WORK_LOG_TRANSLATION'::character varying, 'SAFETY_COURSE'::character varying, 'CHECKLIST_ITEM'::character varying])::text[]))),
    CONSTRAINT document_chunks_visibility_check CHECK (((visibility)::text = ANY ((ARRAY['PUBLIC'::character varying, 'OWNER'::character varying])::text[])))
);


--
-- Name: equipment; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.equipment (
    equipment_id bigint NOT NULL,
    name character varying(100) NOT NULL,
    nfc_tag character varying(100) NOT NULL,
    qr_code character varying(100) NOT NULL
);


--
-- Name: equipment_equipment_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.equipment ALTER COLUMN equipment_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.equipment_equipment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: flyway_schema_history; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.flyway_schema_history (
    installed_rank integer NOT NULL,
    version character varying(50),
    description character varying(200) NOT NULL,
    type character varying(20) NOT NULL,
    script character varying(1000) NOT NULL,
    checksum integer,
    installed_by character varying(100) NOT NULL,
    installed_on timestamp without time zone DEFAULT now() NOT NULL,
    execution_time integer NOT NULL,
    success boolean NOT NULL
);


--
-- Name: log_images; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.log_images (
    imgae_id bigint NOT NULL,
    image_url character varying(255),
    log_id bigint
);


--
-- Name: log_images_imgae_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.log_images ALTER COLUMN imgae_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.log_images_imgae_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: refresh_token; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.refresh_token (
    user_id character varying(255) NOT NULL,
    token character varying(512) NOT NULL
);


--
-- Name: safety_courses; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.safety_courses (
    course_id integer NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    created_by character varying(50),
    description text,
    duration_minutes integer,
    material_url character varying(255),
    title character varying(255) NOT NULL,
    video_url character varying(255) NOT NULL
);


--
-- Name: safety_courses_course_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.safety_courses ALTER COLUMN course_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.safety_courses_course_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: safety_enrollments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.safety_enrollments (
    enrollment_id integer NOT NULL,
    completion_date timestamp(6) without time zone,
    enrolled_at timestamp(6) without time zone,
    status character varying(255) NOT NULL,
    course_id integer,
    user_id character varying(50) NOT NULL,
    CONSTRAINT safety_enrollments_status_check CHECK (((status)::text = ANY ((ARRAY['WATCHED'::character varying, 'UNWATCHED'::character varying, 'WATCHING'::character varying])::text[])))
);


--
-- Name: safety_enrollments_enrollment_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.safety_enrollments ALTER COLUMN enrollment_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.safety_enrollments_enrollment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    user_id character varying(50) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    language_code character varying(255) NOT NULL,
    name character varying(10) NOT NULL,
    password character varying(256) NOT NULL,
    remaining_leave_days integer NOT NULL,
    role character varying(255) NOT NULL,
    ship_yard_area character varying(100) NOT NULL,
    tts_enabled boolean NOT NULL,
    work_shift character varying(255),
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['USER'::character varying, 'ADMIN'::character varying])::text[]))),
    CONSTRAINT users_work_shift_check CHECK (((work_shift)::text = ANY ((ARRAY['MORNING'::character varying, 'AFTERNOON'::character varying, 'NIGHT'::character varying])::text[])))
);


--
-- Name: work_calendar; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.work_calendar (
    calendar_date date NOT NULL,
    day_type character varying(20) NOT NULL,
    description character varying(100),
    CONSTRAINT work_calendar_day_type_check CHECK (((day_type)::text = ANY ((ARRAY['WORKDAY'::character varying, 'WEEKEND'::character varying, 'HOLIDAY'::character varying, 'COMPANY_HOLIDAY'::character varying])::text[])))
);


--
-- Name: work_log_comments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.work_log_comments (
    comment_id bigint NOT NULL,
    content text NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    log_id bigint NOT NULL,
    user_id character varying(50) NOT NULL
);


--
-- Name: work_log_comments_comment_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.work_log_comments ALTER COLUMN comment_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.work_log_comments_comment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: work_log_images; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.work_log_images (
    id bigint NOT NULL,
    image_url character varying(255),
    work_log_id bigint
);


--
-- Name: work_log_images_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.work_log_images ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.work_log_images_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: work_log_translations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.work_log_translations (
    translation_id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    language_code character varying(10),
    original_text text,
    original_title text,
    trace_id character varying(255),
    translated_text text,
    translated_title text,
    updated_at timestamp(6) without time zone,
    user_id character varying(255),
    log_id bigint
);


--
-- Name: work_log_translations_translation_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.work_log_translations ALTER COLUMN translation_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.work_log_translations_translation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: work_logs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.work_logs (
    log_id bigint NOT NULL,
    audio_file_url character varying(255),
    created_at timestamp(6) without time zone NOT NULL,
    log_text text NOT NULL,
    title character varying(256) NOT NULL,
    updated_at timestamp(6) without time zone,
    equipment_id bigint,
    user_id character varying(50)
);


--
-- Name: work_logs_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.work_logs ALTER COLUMN log_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.work_logs_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: absence_requests absence_requests_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.absence_requests
    ADD CONSTRAINT absence_requests_pkey PRIMARY KEY (request_id);


--
-- Name: attendance attendance_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attendance
    ADD CONSTRAINT attendance_pkey PRIMARY KEY (id);


--
-- Name: authority authority_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.authority
    ADD CONSTRAINT authority_pkey PRIMARY KEY (log_id);


--
-- Name: bench_leave_balance bench_leave_balance_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bench_leave_balance
    ADD CONSTRAINT bench_leave_balance_pkey PRIMARY KEY (user_id);


--
-- Name: chat_history chat_history_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_history
    ADD CONSTRAINT chat_history_pkey PRIMARY KEY (id);


--
-- Name: chat_members chat_members_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_members
    ADD CONSTRAINT chat_members_pkey PRIMARY KEY (id);


--
-- Name: chat_messages chat_messages_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_messages
    ADD CONSTRAINT chat_messages_pkey PRIMARY KEY (message_id);


--
-- Name: chat_rooms chat_rooms_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_rooms
    ADD CONSTRAINT chat_rooms_pkey PRIMARY KEY (room_id);


--
-- Name: checklist_items checklist_items_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.checklist_items
    ADD CONSTRAINT checklist_items_pkey PRIMARY KEY (item_id);


--
-- Name: checklist_results checklist_results_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.checklist_results
    ADD CONSTRAINT checklist_results_pkey PRIMARY KEY (result_id);


--
-- Name: checklists checklists_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.checklists
    ADD CONSTRAINT checklists_pkey PRIMARY KEY (checklist_id);


--
-- Name: document_chunks document_chunks_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.document_chunks
    ADD CONSTRAINT document_chunks_pkey PRIMARY KEY (chunk_id);


--
-- Name: equipment equipment_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.equipment
    ADD CONSTRAINT equipment_pkey PRIMARY KEY (equipment_id);


--
-- Name: flyway_schema_history flyway_schema_history_pk; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.flyway_schema_history
    ADD CONSTRAINT flyway_schema_history_pk PRIMARY KEY (installed_rank);


--
-- Name: log_images log_images_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.log_images
    ADD CONSTRAINT log_images_pkey PRIMARY KEY (imgae_id);


--
-- Name: refresh_token refresh_token_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refresh_token
    ADD CONSTRAINT refresh_token_pkey PRIMARY KEY (user_id);


--
-- Name: safety_courses safety_courses_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.safety_courses
    ADD CONSTRAINT safety_courses_pkey PRIMARY KEY (course_id);


--
-- Name: safety_enrollments safety_enrollments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.safety_enrollments
    ADD CONSTRAINT safety_enrollments_pkey PRIMARY KEY (enrollment_id);


--
-- Name: attendance uk_attendance_user_workdate; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attendance
    ADD CONSTRAINT uk_attendance_user_workdate UNIQUE (user_id, work_date);


--
-- Name: checklists uk_checklist_equipment_phase; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.checklists
    ADD CONSTRAINT uk_checklist_equipment_phase UNIQUE (equipment_id, phase);


--
-- Name: document_chunks uk_chunk_source; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.document_chunks
    ADD CONSTRAINT uk_chunk_source UNIQUE (source_type, source_id, chunk_index, embedding_model);


--
-- Name: work_log_translations uk_log_lang; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.work_log_translations
    ADD CONSTRAINT uk_log_lang UNIQUE (log_id, language_code);


--
-- Name: equipment ukro1tbcwkxc529px4l9vd3h2kg; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.equipment
    ADD CONSTRAINT ukro1tbcwkxc529px4l9vd3h2kg UNIQUE (nfc_tag);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (user_id);


--
-- Name: work_calendar work_calendar_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.work_calendar
    ADD CONSTRAINT work_calendar_pkey PRIMARY KEY (calendar_date);


--
-- Name: work_log_comments work_log_comments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.work_log_comments
    ADD CONSTRAINT work_log_comments_pkey PRIMARY KEY (comment_id);


--
-- Name: work_log_images work_log_images_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.work_log_images
    ADD CONSTRAINT work_log_images_pkey PRIMARY KEY (id);


--
-- Name: work_log_translations work_log_translations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.work_log_translations
    ADD CONSTRAINT work_log_translations_pkey PRIMARY KEY (translation_id);


--
-- Name: work_logs work_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.work_logs
    ADD CONSTRAINT work_logs_pkey PRIMARY KEY (log_id);


--
-- Name: flyway_schema_history_s_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX flyway_schema_history_s_idx ON public.flyway_schema_history USING btree (success);


--
-- Name: idx_chunk_embedding_hnsw; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_chunk_embedding_hnsw ON public.document_chunks USING hnsw (embedding public.vector_cosine_ops);


--
-- Name: idx_chunk_model; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_chunk_model ON public.document_chunks USING btree (embedding_model);


--
-- Name: idx_chunk_source; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_chunk_source ON public.document_chunks USING btree (source_type, source_id);


--
-- Name: idx_chunk_visibility; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_chunk_visibility ON public.document_chunks USING btree (visibility, owner_user_id);


--
-- Name: idx_room_sent; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_room_sent ON public.chat_messages USING btree (room_id, sent_at);


--
-- Name: checklist_results fk1avwnej3yunabi1jg6lj2hu2w; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.checklist_results
    ADD CONSTRAINT fk1avwnej3yunabi1jg6lj2hu2w FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- Name: absence_requests fk1n5mhj1m014456pelfv3b5v6q; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.absence_requests
    ADD CONSTRAINT fk1n5mhj1m014456pelfv3b5v6q FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- Name: checklists fk1nvyyp4pxgyxn0qvpfh40q8vq; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.checklists
    ADD CONSTRAINT fk1nvyyp4pxgyxn0qvpfh40q8vq FOREIGN KEY (equipment_id) REFERENCES public.equipment(equipment_id);


--
-- Name: safety_enrollments fk5rykewxobgrcyh9bwxfjjvwh4; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.safety_enrollments
    ADD CONSTRAINT fk5rykewxobgrcyh9bwxfjjvwh4 FOREIGN KEY (course_id) REFERENCES public.safety_courses(course_id);


--
-- Name: authority fk6oocrieb766mdteseb5ma5ko7; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.authority
    ADD CONSTRAINT fk6oocrieb766mdteseb5ma5ko7 FOREIGN KEY (member_id) REFERENCES public.users(user_id);


--
-- Name: checklist_results fk7pp5pl7fjwl3iuaesq27ht8pm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.checklist_results
    ADD CONSTRAINT fk7pp5pl7fjwl3iuaesq27ht8pm FOREIGN KEY (checklist_item_id) REFERENCES public.checklist_items(item_id);


--
-- Name: work_log_comments fk8d48cu8ek1jpcpnnalsfgcil5; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.work_log_comments
    ADD CONSTRAINT fk8d48cu8ek1jpcpnnalsfgcil5 FOREIGN KEY (log_id) REFERENCES public.work_logs(log_id);


--
-- Name: work_log_translations fkam4vb4pyfa2yy5upluvi1s9c; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.work_log_translations
    ADD CONSTRAINT fkam4vb4pyfa2yy5upluvi1s9c FOREIGN KEY (log_id) REFERENCES public.work_logs(log_id);


--
-- Name: work_logs fkc5okyrpk0n5u7eas7vom7g65j; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.work_logs
    ADD CONSTRAINT fkc5okyrpk0n5u7eas7vom7g65j FOREIGN KEY (equipment_id) REFERENCES public.equipment(equipment_id);


--
-- Name: chat_members fke0a4ocat8hcxc20kt2m95qejk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_members
    ADD CONSTRAINT fke0a4ocat8hcxc20kt2m95qejk FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- Name: absence_requests fkgtkc04m3ov8j91tpukh3y4o2u; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.absence_requests
    ADD CONSTRAINT fkgtkc04m3ov8j91tpukh3y4o2u FOREIGN KEY (processed_by) REFERENCES public.users(user_id);


--
-- Name: chat_messages fkhalwepod3944695ji0suwoqb9; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_messages
    ADD CONSTRAINT fkhalwepod3944695ji0suwoqb9 FOREIGN KEY (room_id) REFERENCES public.chat_rooms(room_id) ON DELETE CASCADE;


--
-- Name: safety_enrollments fki0awsnn86bee3mqc1el7wxvcs; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.safety_enrollments
    ADD CONSTRAINT fki0awsnn86bee3mqc1el7wxvcs FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- Name: log_images fkio7y4tphymrolx5i9wrelydjo; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.log_images
    ADD CONSTRAINT fkio7y4tphymrolx5i9wrelydjo FOREIGN KEY (log_id) REFERENCES public.work_logs(log_id);


--
-- Name: attendance fkjcaqd29v2qy723owsdah2t8vx; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attendance
    ADD CONSTRAINT fkjcaqd29v2qy723owsdah2t8vx FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- Name: work_log_comments fkk9mkswotwfnivr7yjp1itl4x6; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.work_log_comments
    ADD CONSTRAINT fkk9mkswotwfnivr7yjp1itl4x6 FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- Name: checklist_items fkosaywfe8917yt4yapp57fxqf9; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.checklist_items
    ADD CONSTRAINT fkosaywfe8917yt4yapp57fxqf9 FOREIGN KEY (checklist_id) REFERENCES public.checklists(checklist_id);


--
-- Name: work_logs fkow2mxee07ckvecl4jiemar1dn; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.work_logs
    ADD CONSTRAINT fkow2mxee07ckvecl4jiemar1dn FOREIGN KEY (user_id) REFERENCES public.users(user_id);


--
-- Name: chat_members fkoww5qci3v6n6dxqmbwte0rdbn; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_members
    ADD CONSTRAINT fkoww5qci3v6n6dxqmbwte0rdbn FOREIGN KEY (room_id) REFERENCES public.chat_rooms(room_id);


--
-- Name: work_log_images fkqqwmv3nrjicjhvx7r0nbmjish; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.work_log_images
    ADD CONSTRAINT fkqqwmv3nrjicjhvx7r0nbmjish FOREIGN KEY (work_log_id) REFERENCES public.work_logs(log_id);


--
-- PostgreSQL database dump complete
--

\unrestrict cpzfiLeZvkNnIA33XXGc3xcQ7QgtYMZnU09uiE2OiJDykK5fdXgEJMKsQ6LDO5w

