-- ADR-0011 — 체크리스트에 점검 회차(run)를 넣는다.
--
-- 무엇이 없었나
--   checklist_results는 (항목, 사용자, 체크, 시각)뿐이라 "누가 언제 어떤 점검을 한 번 수행했는가"를 묶는 키가 없었다.
--   "현재 상태"는 항목별 MAX(result_id)를 템플릿 전역에서 뽑았으므로 A가 월요일에 체크한 작업 전 점검이
--   화요일 B에게 체크된 채로 보였고, "완료"라는 개념이 없어 "이 작업 전에 점검을 했는가"에 답할 수 없었다.
--
-- 점검은 템플릿의 상태가 아니라 한 사람이 한 번 수행한 사건이다. 그 사건이 checklist_runs이고, 결과는 거기 속한다.

-- ---------------------------------------------------------------- 1. 회차

CREATE TABLE checklist_runs (
    run_id        bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    checklist_id  integer                        NOT NULL,
    user_id       character varying(50)          NOT NULL,
    started_at    timestamp(6) without time zone NOT NULL,
    -- 닫힘은 둘이 한 쌍이다. 열려 있으면 둘 다 NULL(IN_PROGRESS), 닫혔으면 outcome이 곧 상태다.
    closed_at     timestamp(6) without time zone,
    outcome       character varying(20),
    CONSTRAINT checklist_runs_pkey PRIMARY KEY (run_id),
    CONSTRAINT checklist_runs_outcome_check CHECK (outcome IN ('COMPLETED', 'ABANDONED')),
    CONSTRAINT checklist_runs_closed_pair_check CHECK ((closed_at IS NULL) = (outcome IS NULL)),
    CONSTRAINT fk_checklist_runs_checklist FOREIGN KEY (checklist_id) REFERENCES checklists(checklist_id),
    CONSTRAINT fk_checklist_runs_user      FOREIGN KEY (user_id)      REFERENCES users(user_id)
);

-- 한 사람은 같은 템플릿의 열린 회차를 하나만 가진다. 더블탭·재접속이 같은 회차로 돌아오고,
-- 동시에 두 번 열면 한쪽이 여기 걸려 서비스가 이긴 쪽을 다시 찾는다(ChecklistRunService.open).
CREATE UNIQUE INDEX uq_checklist_runs_open
    ON checklist_runs (checklist_id, user_id)
 WHERE closed_at IS NULL;

-- 장비별 최근 점검(관리자 목록)과 내 점검 목록.
CREATE INDEX idx_checklist_runs_checklist ON checklist_runs (checklist_id, started_at DESC);
CREATE INDEX idx_checklist_runs_user      ON checklist_runs (user_id, started_at DESC);

-- ---------------------------------------------------------------- 2. 결과를 회차에 붙인다

ALTER TABLE checklist_results ADD COLUMN run_id bigint;

-- 기존 결과의 회차는 (템플릿, 사용자, 체크한 날짜)로 근사한다 — 그때는 회차가 없었으니 정확한 경계는 알 수 없고,
-- "같은 사람이 같은 날 같은 템플릿에 남긴 체크"가 가장 가까운 묶음이다. 전부 COMPLETED로 닫는다:
-- 열어 두면 부분 유니크에 걸려 그 사람이 오늘 새 회차를 못 연다. 시드에는 결과 행이 없어 로컬은 0건이다.
DO $$
DECLARE
    orphans bigint;
    created bigint;
BEGIN
    INSERT INTO checklist_runs (checklist_id, user_id, started_at, closed_at, outcome)
    SELECT i.checklist_id, r.user_id, MIN(r.checked_at), MAX(r.checked_at), 'COMPLETED'
      FROM checklist_results r
      JOIN checklist_items i ON i.item_id = r.checklist_item_id
     GROUP BY i.checklist_id, r.user_id, r.checked_at::date;
    GET DIAGNOSTICS created = ROW_COUNT;

    UPDATE checklist_results r
       SET run_id = run.run_id
      FROM checklist_items i, checklist_runs run
     WHERE i.item_id = r.checklist_item_id
       AND run.checklist_id = i.checklist_id
       AND run.user_id = r.user_id
       AND run.started_at::date = r.checked_at::date
       AND r.run_id IS NULL;

    SELECT count(*) INTO orphans FROM checklist_results WHERE run_id IS NULL;
    IF orphans > 0 THEN
        RAISE EXCEPTION 'checklist_results에 회차를 못 찾은 행이 % 건 있다. 위 GROUP BY와 UPDATE의 조건이 어긋났다 — 확인 뒤 다시 실행하라.', orphans;
    END IF;

    RAISE NOTICE 'checklist_runs 백필: 회차 % 개 생성', created;
END $$;

ALTER TABLE checklist_results ALTER COLUMN run_id SET NOT NULL;
ALTER TABLE checklist_results ADD CONSTRAINT fk_checklist_results_run FOREIGN KEY (run_id) REFERENCES checklist_runs(run_id);

-- 회차 안의 항목별 최신(MAX(result_id) GROUP BY item)이 이 인덱스를 탄다.
CREATE INDEX idx_checklist_results_run_item ON checklist_results (run_id, checklist_item_id, result_id DESC);

-- 자식 FK 컬럼 인덱스 — V3·V4가 work_logs·users 자식에 한 것과 같은 이유. 항목 삭제 가드(existsByChecklistItem_ItemId)와
-- 항목 삭제 시 FK 검사가 이걸 쓴다. 지금까지 없었다.
CREATE INDEX IF NOT EXISTS idx_checklist_results_item ON checklist_results (checklist_item_id);
