-- V2: ddl-auto가 만들던 나머지 테이블 전부를 마이그레이션으로 옮긴다 (백로그 P0-13-3)
--
-- V1은 document_chunks 하나만 담당했고, 나머지 21개 테이블은 소스 오브 트루스가
-- JPA 엔티티뿐이었다. 그래서 스키마 변경이 리뷰 대상이 아니었고,
-- ddl-auto=update가 반영하지 못하는 변경(컬럼 삭제 / 타입 변경 / NOT NULL 완화)은
-- 조용히 어긋난 채로 남았다.
--
-- 이 파일이 들어오면서 ddl-auto를 validate로 내렸다. 이제 엔티티와 DB가 어긋나면
-- 기동이 실패한다. 앞으로 스키마를 바꾸려면 V3, V4... 를 직접 써야 한다 --
-- 그것이 비용이 아니라 목적이다.
--
-- ## 이 파일은 손으로 쓰지 않았다
--
-- Hibernate가 실제로 만든 DDL을 pg_dump로 뽑아 기계적으로 변환했다.
-- 손으로 옮기면 컬럼 하나만 어긋나도 validate가 터질 때까지 알 수 없기 때문이다.
-- 변환 결과는 빈 DB에 V1+V2를 적용한 뒤 원본 덤프와 diff로 대조해 확인했다.
--
-- ## 기존 DB에서도 안전하다
--
-- 모든 문장이 멱등이다. 테이블은 IF NOT EXISTS, 인덱스도 IF NOT EXISTS,
-- 외래키는 PostgreSQL에 ADD CONSTRAINT IF NOT EXISTS가 없어 duplicate_object만 삼킨다.
--
-- ## 형태에 대한 두 가지 결정
--
-- 1. PK / UNIQUE / CHECK / IDENTITY 를 CREATE TABLE 안으로 접었다.
--    pg_dump는 이들을 별도 ALTER로 내보내는데, 그대로 두면 문장마다 멱등 처리를
--    따로 해야 한다. 인라인이면 CREATE TABLE IF NOT EXISTS 하나로 끝난다.
--
-- 2. 외래키만 맨 뒤에 남겼다.
--    인라인으로 접으면 참조 대상 테이블이 먼저 생성되어야 해서 생성 순서를 맞춰야 한다.
--    뒤에서 한 번에 걸면 순서 문제가 사라진다.
--
-- ## 제외한 것
--
--   document_chunks / document_chunk_seq / 관련 인덱스 -- V1이 관리한다
--   flyway_schema_history                             -- Flyway 자체 관리
--   bench_leave_balance                               -- LeaveBalanceConcurrencyTest가 만든다.
--                                                        엔티티가 없어 애플리케이션과 무관하다
--   pg_stat_statements 확장                            -- 진단 도구이며 앱 스키마가 아니다.
--                                                        shared_preload_libraries가 필요해
--                                                        없는 환경에서는 CREATE EXTENSION이 실패한다
--
-- 외래키 이름(fk1avwnej3...)은 Hibernate가 테이블·컬럼에서 결정론적으로 만든 해시다.
-- 읽기 나쁘지만 바꾸지 않는다 -- 바꾸면 update가 돌던 기존 DB와 이름이 어긋난다.

-- 시퀀스

CREATE SEQUENCE IF NOT EXISTS attendance_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

-- 테이블 (PK / UNIQUE / CHECK / IDENTITY 인라인)

CREATE TABLE IF NOT EXISTS absence_requests (
    request_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    decision_comment character varying(255),
    document_url character varying(255),
    end_date date NOT NULL,
    processed_at timestamp(6) without time zone,
    reason character varying(255) NOT NULL,
    requested_at timestamp(6) without time zone,
    start_date date NOT NULL,
    status character varying(20) NOT NULL,
    request_type character varying(20) NOT NULL,
    user_id character varying(50) NOT NULL,
    processed_by character varying(50),
    CONSTRAINT absence_requests_request_type_check CHECK (request_type IN ('VACATION', 'SICK')),
    CONSTRAINT absence_requests_status_check CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED')),
    CONSTRAINT absence_requests_pkey PRIMARY KEY (request_id)
);

CREATE TABLE IF NOT EXISTS attendance (
    id bigint NOT NULL,
    clock_in_time timestamp(6) without time zone,
    clock_out_time timestamp(6) without time zone,
    in_location character varying(255),
    out_location character varying(255),
    status character varying(20) NOT NULL,
    total_work_time character varying(255),
    work_date date NOT NULL,
    user_id character varying(50) NOT NULL,
    CONSTRAINT attendance_status_check CHECK (status IN ('NORMAL', 'LATE', 'LEFT_EARLY', 'ABSENT', 'VACATION', 'SICK')),
    CONSTRAINT attendance_pkey PRIMARY KEY (id),
    CONSTRAINT uk_attendance_user_workdate UNIQUE (user_id, work_date)
);

CREATE TABLE IF NOT EXISTS authority (
    log_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    authority smallint,
    member_id character varying(50),
    CONSTRAINT authority_authority_check CHECK (((authority >= 0) AND (authority <= 1))),
    CONSTRAINT authority_pkey PRIMARY KEY (log_id)
);

CREATE TABLE IF NOT EXISTS chat_history (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp(6) without time zone,
    reply text,
    retrieval_mode character varying(16),
    source_chunk_ids text,
    trace_id character varying(255),
    user_id character varying(255),
    user_query text,
    CONSTRAINT chat_history_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS chat_members (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    joined_at timestamp(6) without time zone,
    last_read_time timestamp(6) without time zone,
    room_id integer NOT NULL,
    user_id character varying(50) NOT NULL,
    CONSTRAINT chat_members_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS chat_messages (
    message_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    content text NOT NULL,
    file_url character varying(255),
    message_type character varying(255) NOT NULL,
    sender_id character varying(255) NOT NULL,
    sent_at timestamp(6) without time zone,
    room_id integer NOT NULL,
    CONSTRAINT chat_messages_message_type_check CHECK (message_type IN ('TEXT', 'IMAGE', 'FILE')),
    CONSTRAINT chat_messages_pkey PRIMARY KEY (message_id)
);

CREATE TABLE IF NOT EXISTS chat_rooms (
    room_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp(6) without time zone,
    creator_id character varying(255),
    is_group boolean,
    last_message_at timestamp(6) without time zone,
    last_message_content character varying(255),
    room_name character varying(255),
    CONSTRAINT chat_rooms_pkey PRIMARY KEY (room_id)
);

CREATE TABLE IF NOT EXISTS checklist_items (
    item_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    content character varying(255) NOT NULL,
    sequence integer NOT NULL,
    checklist_id integer NOT NULL,
    CONSTRAINT checklist_items_pkey PRIMARY KEY (item_id)
);

CREATE TABLE IF NOT EXISTS checklist_results (
    result_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    checked_at timestamp(6) without time zone NOT NULL,
    is_checked boolean NOT NULL,
    checklist_item_id integer NOT NULL,
    user_id character varying(50) NOT NULL,
    CONSTRAINT checklist_results_pkey PRIMARY KEY (result_id)
);

CREATE TABLE IF NOT EXISTS checklists (
    checklist_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp(6) without time zone,
    phase character varying(10) NOT NULL,
    title character varying(100) NOT NULL,
    updated_at timestamp(6) without time zone,
    equipment_id bigint NOT NULL,
    CONSTRAINT checklists_phase_check CHECK (phase IN ('PRE', 'POST')),
    CONSTRAINT checklists_pkey PRIMARY KEY (checklist_id),
    CONSTRAINT uk_checklist_equipment_phase UNIQUE (equipment_id, phase)
);

CREATE TABLE IF NOT EXISTS equipment (
    equipment_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name character varying(100) NOT NULL,
    nfc_tag character varying(100) NOT NULL,
    qr_code character varying(100) NOT NULL,
    CONSTRAINT equipment_pkey PRIMARY KEY (equipment_id),
    CONSTRAINT ukro1tbcwkxc529px4l9vd3h2kg UNIQUE (nfc_tag)
);

CREATE TABLE IF NOT EXISTS log_images (
    imgae_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    image_url character varying(255),
    log_id bigint,
    CONSTRAINT log_images_pkey PRIMARY KEY (imgae_id)
);

CREATE TABLE IF NOT EXISTS refresh_token (
    user_id character varying(255) NOT NULL,
    token character varying(512) NOT NULL,
    CONSTRAINT refresh_token_pkey PRIMARY KEY (user_id)
);

CREATE TABLE IF NOT EXISTS safety_courses (
    course_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    created_by character varying(50),
    description text,
    duration_minutes integer,
    material_url character varying(255),
    title character varying(255) NOT NULL,
    video_url character varying(255) NOT NULL,
    CONSTRAINT safety_courses_pkey PRIMARY KEY (course_id)
);

CREATE TABLE IF NOT EXISTS safety_enrollments (
    enrollment_id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    completion_date timestamp(6) without time zone,
    enrolled_at timestamp(6) without time zone,
    status character varying(255) NOT NULL,
    course_id integer,
    user_id character varying(50) NOT NULL,
    CONSTRAINT safety_enrollments_status_check CHECK (status IN ('WATCHED', 'UNWATCHED', 'WATCHING')),
    CONSTRAINT safety_enrollments_pkey PRIMARY KEY (enrollment_id)
);

CREATE TABLE IF NOT EXISTS users (
    user_id character varying(50) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    language_code character varying(255) NOT NULL,
    name character varying(10) NOT NULL,
    password character varying(256) NOT NULL,
    remaining_leave_days integer NOT NULL,
    role character varying(255) NOT NULL,
    ship_yard_area character varying(100) NOT NULL,
    tts_enabled boolean NOT NULL,
    work_shift character varying(255),
    CONSTRAINT users_role_check CHECK (role IN ('USER', 'ADMIN')),
    CONSTRAINT users_work_shift_check CHECK (work_shift IN ('MORNING', 'AFTERNOON', 'NIGHT')),
    CONSTRAINT users_pkey PRIMARY KEY (user_id)
);

CREATE TABLE IF NOT EXISTS work_calendar (
    calendar_date date NOT NULL,
    day_type character varying(20) NOT NULL,
    description character varying(100),
    CONSTRAINT work_calendar_day_type_check CHECK (day_type IN ('WORKDAY', 'WEEKEND', 'HOLIDAY', 'COMPANY_HOLIDAY')),
    CONSTRAINT work_calendar_pkey PRIMARY KEY (calendar_date)
);

CREATE TABLE IF NOT EXISTS work_log_comments (
    comment_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    content text NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    log_id bigint NOT NULL,
    user_id character varying(50) NOT NULL,
    CONSTRAINT work_log_comments_pkey PRIMARY KEY (comment_id)
);

CREATE TABLE IF NOT EXISTS work_log_images (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    image_url character varying(255),
    work_log_id bigint,
    CONSTRAINT work_log_images_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS work_log_translations (
    translation_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp(6) without time zone,
    language_code character varying(10),
    original_text text,
    original_title text,
    trace_id character varying(255),
    translated_text text,
    translated_title text,
    updated_at timestamp(6) without time zone,
    user_id character varying(255),
    log_id bigint,
    CONSTRAINT uk_log_lang UNIQUE (log_id, language_code),
    CONSTRAINT work_log_translations_pkey PRIMARY KEY (translation_id)
);

CREATE TABLE IF NOT EXISTS work_logs (
    log_id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    audio_file_url character varying(255),
    created_at timestamp(6) without time zone NOT NULL,
    log_text text NOT NULL,
    title character varying(256) NOT NULL,
    updated_at timestamp(6) without time zone,
    equipment_id bigint,
    user_id character varying(50),
    CONSTRAINT work_logs_pkey PRIMARY KEY (log_id)
);

-- 인덱스

CREATE INDEX IF NOT EXISTS idx_room_sent ON chat_messages USING btree (room_id, sent_at);

-- 외래키 (참조 순서를 피하려 맨 뒤에서 건다)

DO $$ BEGIN
    ALTER TABLE absence_requests ADD CONSTRAINT fk1n5mhj1m014456pelfv3b5v6q FOREIGN KEY (user_id) REFERENCES users(user_id);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    ALTER TABLE absence_requests ADD CONSTRAINT fkgtkc04m3ov8j91tpukh3y4o2u FOREIGN KEY (processed_by) REFERENCES users(user_id);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    ALTER TABLE attendance ADD CONSTRAINT fkjcaqd29v2qy723owsdah2t8vx FOREIGN KEY (user_id) REFERENCES users(user_id);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    ALTER TABLE authority ADD CONSTRAINT fk6oocrieb766mdteseb5ma5ko7 FOREIGN KEY (member_id) REFERENCES users(user_id);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    ALTER TABLE chat_members ADD CONSTRAINT fke0a4ocat8hcxc20kt2m95qejk FOREIGN KEY (user_id) REFERENCES users(user_id);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    ALTER TABLE chat_members ADD CONSTRAINT fkoww5qci3v6n6dxqmbwte0rdbn FOREIGN KEY (room_id) REFERENCES chat_rooms(room_id);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    ALTER TABLE chat_messages ADD CONSTRAINT fkhalwepod3944695ji0suwoqb9 FOREIGN KEY (room_id) REFERENCES chat_rooms(room_id) ON DELETE CASCADE;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    ALTER TABLE checklist_items ADD CONSTRAINT fkosaywfe8917yt4yapp57fxqf9 FOREIGN KEY (checklist_id) REFERENCES checklists(checklist_id);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    ALTER TABLE checklist_results ADD CONSTRAINT fk1avwnej3yunabi1jg6lj2hu2w FOREIGN KEY (user_id) REFERENCES users(user_id);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    ALTER TABLE checklist_results ADD CONSTRAINT fk7pp5pl7fjwl3iuaesq27ht8pm FOREIGN KEY (checklist_item_id) REFERENCES checklist_items(item_id);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    ALTER TABLE checklists ADD CONSTRAINT fk1nvyyp4pxgyxn0qvpfh40q8vq FOREIGN KEY (equipment_id) REFERENCES equipment(equipment_id);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    ALTER TABLE log_images ADD CONSTRAINT fkio7y4tphymrolx5i9wrelydjo FOREIGN KEY (log_id) REFERENCES work_logs(log_id);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    ALTER TABLE safety_enrollments ADD CONSTRAINT fk5rykewxobgrcyh9bwxfjjvwh4 FOREIGN KEY (course_id) REFERENCES safety_courses(course_id);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    ALTER TABLE safety_enrollments ADD CONSTRAINT fki0awsnn86bee3mqc1el7wxvcs FOREIGN KEY (user_id) REFERENCES users(user_id);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    ALTER TABLE work_log_comments ADD CONSTRAINT fk8d48cu8ek1jpcpnnalsfgcil5 FOREIGN KEY (log_id) REFERENCES work_logs(log_id);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    ALTER TABLE work_log_comments ADD CONSTRAINT fkk9mkswotwfnivr7yjp1itl4x6 FOREIGN KEY (user_id) REFERENCES users(user_id);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    ALTER TABLE work_log_images ADD CONSTRAINT fkqqwmv3nrjicjhvx7r0nbmjish FOREIGN KEY (work_log_id) REFERENCES work_logs(log_id);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    ALTER TABLE work_log_translations ADD CONSTRAINT fkam4vb4pyfa2yy5upluvi1s9c FOREIGN KEY (log_id) REFERENCES work_logs(log_id);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    ALTER TABLE work_logs ADD CONSTRAINT fkc5okyrpk0n5u7eas7vom7g65j FOREIGN KEY (equipment_id) REFERENCES equipment(equipment_id);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$ BEGIN
    ALTER TABLE work_logs ADD CONSTRAINT fkow2mxee07ckvecl4jiemar1dn FOREIGN KEY (user_id) REFERENCES users(user_id);
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
