package com.DOCKin.global.config;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;

import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.util.LinkedHashSet;
import java.util.Set;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.junit.jupiter.api.Assertions.fail;

/**
 * 검증: 로컬 시드({@code db/seed/R__seed_sample.sql})가 <b>조용히 틀려 있지 않은가?</b>
 *
 * <h3>왜 DB 없이 파일을 읽는가</h3>
 * 시드를 실제로 적용해보는 테스트를 만들면 <b>테스트가 DB에 표본 데이터를 쓴다.</b>
 * 부작용이 다른 테스트로 새기 쉽다 -- 지금은 Testcontainers 컨테이너 하나를
 * 모든 테스트가 공유하므로 더욱 그렇다(P2-11-5 이후).
 *
 * <p>대신 <b>파일을 읽어 검사한다.</b> 아래 두 가지는 정적 검사만으로 잡히고,
 * 둘 다 놓치면 실행 시점에 에러가 나지 않고 나중에 엉뚱한 증상으로 나타나는 종류다.
 *
 * <h3>이 테스트가 잡지 못하는 것</h3>
 * SQL이 실제로 도는지, 컬럼명이 맞는지는 보지 못한다. 그것은 {@code seed} 프로파일로
 * 앱을 한 번 띄우면 Flyway가 알려준다. 삭제된 {@code data.sql}이 <b>세 겹으로 죽어 있던</b>
 * 이유 중 "없는 컬럼을 참조"는 이 방식으로는 못 잡는다는 뜻이기도 하다.
 */
class SeedDataTest {

    private static final String SEED_PATH = "db/seed/R__seed_sample.sql";

    /** 시드가 심는 비밀번호. 바꾸려면 SQL의 해시와 이 값을 함께 바꿔야 한다. */
    private static final String SEED_PASSWORD = "dockin1234";

    /**
     * PK에 시퀀스가 없어 {@code setval} 대상이 아닌 표.
     *
     * <ul>
     *   <li>{@code users} — PK가 문자열({@code user_id})이다</li>
     *   <li>{@code work_calendar} — PK가 날짜(자연키)다</li>
     *   <li>{@code attendance} — IDENTITY가 아니라 {@code attendance_seq}를 쓴다.
     *       그래서 {@code pg_get_serial_sequence}가 아니라 시퀀스 이름을 직접 준다</li>
     * </ul>
     */
    private static final Set<String> NO_IDENTITY_SEQUENCE =
            Set.of("users", "work_calendar", "attendance");

    private final String seedSql = readSeed();

    /**
     * 해시를 손으로 고치면 <b>로그인만 조용히 안 된다.</b> 시드는 성공하고, 화면도 뜨고,
     * 비밀번호가 틀렸다는 메시지만 나온다 — 원인이 시드에 있다는 것을 떠올리기 어렵다.
     */
    @Test
    @DisplayName("시드 사용자의 BCrypt 해시가 문서화된 비밀번호와 일치한다")
    void 비밀번호_해시_일치() {
        Matcher matcher = Pattern.compile("\\$2[aby]\\$\\d{2}\\$[./A-Za-z0-9]{53}").matcher(seedSql);

        int checked = 0;
        BCryptPasswordEncoder encoder = new BCryptPasswordEncoder();
        while (matcher.find()) {
            String hash = matcher.group();
            assertTrue(encoder.matches(SEED_PASSWORD, hash),
                    "시드의 BCrypt 해시가 '" + SEED_PASSWORD + "'와 맞지 않습니다: " + hash);
            checked++;
        }
        assertTrue(checked > 0, "시드에서 BCrypt 해시를 찾지 못했습니다. " + SEED_PATH + "를 확인하세요.");
    }

    /**
     * PK를 명시해 넣은 표는 반드시 시퀀스를 따라 올려줘야 한다.
     *
     * <p>{@code GENERATED BY DEFAULT AS IDENTITY}는 명시된 값을 <b>받아주기만 하고</b>
     * 시퀀스를 올리지 않는다. 빠뜨리면 시드는 성공하고 화면도 잘 뜨는데,
     * <b>앱이 처음 저장하는 순간</b> 같은 PK를 발급받아 터진다.
     *
     * <p>표를 하나 더 추가하면서 {@code setval}을 빠뜨리는 것이 이 시드에서 가장 하기 쉬운 실수다.
     */
    @Test
    @DisplayName("PK를 명시한 모든 표에 시퀀스 보정(setval)이 있다")
    void 시퀀스_보정_누락_없음() {
        Set<String> inserted = extract("(?i)INSERT\\s+INTO\\s+([a-z_]+)");
        Set<String> setval = extract("(?i)pg_get_serial_sequence\\('([a-z_]+)'");

        assertFalse(inserted.isEmpty(), "시드에서 INSERT 문을 찾지 못했습니다.");

        for (String table : inserted) {
            if (NO_IDENTITY_SEQUENCE.contains(table)) {
                continue;
            }
            if (!setval.contains(table)) {
                fail("""
                        '%s'에 PK를 명시해 INSERT하면서 시퀀스 보정이 없습니다.

                        아래를 %s의 9절에 추가하세요:
                          SELECT setval(pg_get_serial_sequence('%s', '<pk컬럼>'),
                                        GREATEST(COALESCE((SELECT MAX(<pk컬럼>) FROM %s), 1), 1));

                        빠뜨리면 시드는 성공하고, 앱이 처음 저장할 때 PK 충돌로 터집니다.
                        """.formatted(table, SEED_PATH, table, table));
            }
        }

        // attendance는 IDENTITY가 아니라 attendance_seq를 쓰므로 위 규칙에서 빠져 있다.
        // 그래서 별도로 확인한다 — 빠지면 증상은 똑같이 PK 충돌이다.
        assertTrue(seedSql.contains("setval('attendance_seq'"),
                "attendance에 PK를 명시해 넣는데 attendance_seq 보정이 없습니다.");
    }

    private Set<String> extract(String regex) {
        Set<String> found = new LinkedHashSet<>();
        Matcher matcher = Pattern.compile(regex).matcher(seedSql);
        while (matcher.find()) {
            found.add(matcher.group(1).toLowerCase());
        }
        return found;
    }

    private String readSeed() {
        try (InputStream in = getClass().getClassLoader().getResourceAsStream(SEED_PATH)) {
            if (in == null) {
                throw new IllegalStateException(
                        SEED_PATH + "을 클래스패스에서 찾을 수 없습니다. 파일이 삭제되었나요?");
            }
            return new String(in.readAllBytes(), StandardCharsets.UTF_8);
        } catch (IOException e) {
            throw new IllegalStateException(SEED_PATH + "을 읽을 수 없습니다.", e);
        }
    }
}
